#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := aws-cpp-sdk-secretsmanager
LOCAL_MODULE_FILENAME := libaws-cpp-sdk-secretsmanager
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  source/SecretsManagerClient.cpp \
  source/SecretsManagerEndpointProvider.cpp \
  source/SecretsManagerEndpointRules.cpp \
  source/SecretsManagerErrorMarshaller.cpp \
  source/SecretsManagerErrors.cpp \
  source/SecretsManagerRequest.cpp \
  source/model/CancelRotateSecretRequest.cpp \
  source/model/CancelRotateSecretResult.cpp \
  source/model/CreateSecretRequest.cpp \
  source/model/CreateSecretResult.cpp \
  source/model/DeleteResourcePolicyRequest.cpp \
  source/model/DeleteResourcePolicyResult.cpp \
  source/model/DeleteSecretRequest.cpp \
  source/model/DeleteSecretResult.cpp \
  source/model/DescribeSecretRequest.cpp \
  source/model/DescribeSecretResult.cpp \
  source/model/Filter.cpp \
  source/model/FilterNameStringType.cpp \
  source/model/GetRandomPasswordRequest.cpp \
  source/model/GetRandomPasswordResult.cpp \
  source/model/GetResourcePolicyRequest.cpp \
  source/model/GetResourcePolicyResult.cpp \
  source/model/GetSecretValueRequest.cpp \
  source/model/GetSecretValueResult.cpp \
  source/model/ListSecretVersionIdsRequest.cpp \
  source/model/ListSecretVersionIdsResult.cpp \
  source/model/ListSecretsRequest.cpp \
  source/model/ListSecretsResult.cpp \
  source/model/PutResourcePolicyRequest.cpp \
  source/model/PutResourcePolicyResult.cpp \
  source/model/PutSecretValueRequest.cpp \
  source/model/PutSecretValueResult.cpp \
  source/model/RemoveRegionsFromReplicationRequest.cpp \
  source/model/RemoveRegionsFromReplicationResult.cpp \
  source/model/ReplicaRegionType.cpp \
  source/model/ReplicateSecretToRegionsRequest.cpp \
  source/model/ReplicateSecretToRegionsResult.cpp \
  source/model/ReplicationStatusType.cpp \
  source/model/RestoreSecretRequest.cpp \
  source/model/RestoreSecretResult.cpp \
  source/model/RotateSecretRequest.cpp \
  source/model/RotateSecretResult.cpp \
  source/model/RotationRulesType.cpp \
  source/model/SecretListEntry.cpp \
  source/model/SecretVersionsListEntry.cpp \
  source/model/SortOrderType.cpp \
  source/model/StatusType.cpp \
  source/model/StopReplicationToReplicaRequest.cpp \
  source/model/StopReplicationToReplicaResult.cpp \
  source/model/Tag.cpp \
  source/model/TagResourceRequest.cpp \
  source/model/UntagResourceRequest.cpp \
  source/model/UpdateSecretRequest.cpp \
  source/model/UpdateSecretResult.cpp \
  source/model/UpdateSecretVersionStageRequest.cpp \
  source/model/UpdateSecretVersionStageResult.cpp \
  source/model/ValidateResourcePolicyRequest.cpp \
  source/model/ValidateResourcePolicyResult.cpp \
  source/model/ValidationErrorsEntry.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include/aws/secretsmanager \
  $(MY_MODULE_PATH)/include/aws/secretsmanager/model \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/bearer-token-provider \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/signer \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/signer-provider \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/client \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/config \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/config/defaults \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/endpoint \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/endpoint/internal \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external/cjson \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external/tinyxml2 \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http/curl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http/standard \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/internal \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/monitoring \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/net \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/platform \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/platform/refs \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/base64 \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/bcrypt \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/commoncrypto \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/event \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/json \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/logging \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/logging/android \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/memory \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/memory/stl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/ratelimiter \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/stream \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/threading \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/xml \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-auth/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-cal/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-common/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-compression/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-event-stream/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-http/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-io/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-io/source \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-mqtt/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-s3/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-sdkutils/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-checksums/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/include \
  $(MY_MODULE_PATH)/../curl/include \
  $(MY_MODULE_PATH)/../curl/include/curl \
  $(MY_MODULE_PATH)/../curl/lib \
  $(MY_MODULE_PATH)/../curl/lib/vauth \
  $(MY_MODULE_PATH)/../curl/lib/vquic \
  $(MY_MODULE_PATH)/../curl/lib/vssh \
  $(MY_MODULE_PATH)/../curl/lib/vtls \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/aws

LOCAL_CFLAGS := -DAWS_SECRETSMANAGER_EXPORTS -DUSE_IMPORT_EXPORT=1


LOCAL_SHARED_LIBRARIES := \
  aws-cpp-sdk-core

include $(BUILD_SHARED_LIBRARY)

