--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: inputdriverMSWINMSG


configuration( { "WIN32" } )
  project( "inputdriverMSWINMSG" )

configuration( { "WIN64" } )
  project( "inputdriverMSWINMSG" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=inputdriverMSWINMSG" } )
  
configuration( { WIN32 } )
links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  

configuration( { WIN32 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVERMSWINMSG_BUILD_MODULE", "MODULE_IS_PLUGIN=1", "MODULE_NAME=inputdriverMSWINMSG" } )
  
configuration( { WIN64 } )
links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  

configuration( { WIN64 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVERMSWINMSG_BUILD_MODULE", "MODULE_IS_PLUGIN=1", "MODULE_NAME=inputdriverMSWINMSG" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainInputDriverMSWINMSG.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainInputDriverMSWINMSG.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
