--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: pubsubpluginMSMQ


configuration( { "WIN32" } )
  project( "pubsubpluginMSMQ" )

configuration( { "WIN64" } )
  project( "pubsubpluginMSMQ" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=pubsubpluginMSMQ" } )
  
configuration( { WIN32 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )
  links( { "Mqrt.lib", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )
  

configuration( { WIN32 } )
defines( { "MODULE_IS_PLUGIN=1", "MODULE_NAME=pubsubpluginMSMQ", "PUBSUBPLUGIN_MSMQ_BUILD_PLUGIN_DLL" } )
  
configuration( { WIN64 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )
  links( { "Mqrt.lib", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )
  

configuration( { WIN64 } )
defines( { "MODULE_IS_PLUGIN=1", "MODULE_NAME=pubsubpluginMSMQ", "PUBSUBPLUGIN_MSMQ_BUILD_PLUGIN_DLL" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/pubsubpluginMSMQ.h",
  "include/pubsubpluginMSMQ_CMsmqPubSubClient.h",
  "include/pubsubpluginMSMQ_CMsmqPubSubClientConfig.h",
  "include/pubsubpluginMSMQ_CMsmqPubSubClientTopic.h",
  "include/pubsubpluginMSMQ_CMsmqPubSubClientTopicConfig.h",
  "include/pubsubpluginMSMQ_config.h",
  "include/pubsubpluginMSMQ_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/pubsubpluginMSMQ.cpp",
  "src/pubsubpluginMSMQ_CMsmqPubSubClient.cpp",
  "src/pubsubpluginMSMQ_CMsmqPubSubClientConfig.cpp",
  "src/pubsubpluginMSMQ_CMsmqPubSubClientTopic.cpp",
  "src/pubsubpluginMSMQ_CMsmqPubSubClientTopicConfig.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCOM/include", "../../../platform/gucefCOMCORE/include", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "../../../platform/gucefPUBSUB/include", "../../../platform/gucefVFS/include", "../../../platform/gucefWEB/include", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCOMCORE/include/mswin", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCOMCORE/include/mswin", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
