--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: main


configuration( { "ANDROID32" } )
  project( "main" )

configuration( { "ANDROID64" } )
  project( "main" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "ANDROID32" } )


configuration( { ANDROID32 } )
kind( "SharedLib" )
configuration( { "ANDROID64" } )


configuration( { ANDROID64 } )
kind( "SharedLib" )
  
configuration( { ANDROID32 } )
links( { "gucefLOADER" } )
  links( { "android", "android_native_app_glue" } )
  

configuration( { ANDROID32 } )
defines( { "MODULE_NAME=main" } )
  
configuration( { ANDROID64 } )
links( { "gucefLOADER" } )
  links( { "android", "android_native_app_glue" } )
  

configuration( { ANDROID64 } )
defines( { "MODULE_NAME=main" } )


configuration( { "ANDROID32" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "main.c"
    } )



configuration( { "ANDROID64" } )
    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "main.c"
    } )


configuration( {} )
includedirs( { "../../..", "../../../../common/include", "../../../gucefCORE", "../../../gucefCORE/include", "../../../gucefCORE/include/", "../../../gucefCORE/include/c_api", "../../../gucefCORE/include/c_api/", "../../../gucefLOADER/include", "../../../gucefMT", "../../../gucefMT/include", "../../../gucefMT/include/" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../gucefCORE/include/", "../../../gucefCORE/include/android", "../../../gucefCORE/include/c_api/", "../../../gucefMT/include/" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../gucefCORE/include/", "../../../gucefCORE/include/android", "../../../gucefCORE/include/c_api/", "../../../gucefMT/include/" } )
