CALL CMakeCommon.bat

ECHO *** Set VS2026 specifics and run CMake ***

SET MAINCMAKE=%SRCROOTDIR%\projects\CMake\targets\GUCEF_tag_services
SET VS18_OUTPUTDIR="%OUTPUTDIR%\VS2026_x64_Services"

CMake.exe -DBUILD_SHARED_LIBS=ON -G"Visual Studio 18 2026" -A x64 -H"%MAINCMAKE%" -B%VS18_OUTPUTDIR% -DCMAKE_POLICY_VERSION_MINIMUM=3.5
PAUSE