CALL CMakeCommon.bat

ECHO *** Set VS2026 specifics and run CMake ***

SET MAINCMAKE=%SRCROOTDIR%\projects\CMake\targets\GUCEF_exe_pubsub2pubsub
SET VS26_OUTPUTDIR="%OUTPUTDIR%\VS2026_x64_pubsub2pubsub"

CMake.exe -DBUILD_SHARED_LIBS=ON -G"Visual Studio 18 2026" -A x64 -H"%MAINCMAKE%" -B%VS26_OUTPUTDIR% -DCMAKE_POLICY_VERSION_MINIMUM=3.5
PAUSE