--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_tag_services" )

  platforms( { "ALL", "ANDROID32", "ANDROID64", "ARDUINO", "EMSCRIPTEN32", "EMSCRIPTEN64", "IOS", "LINUX32", "LINUX64", "OSX", "WIN32", "WIN64" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "dependencies/aws-cpp-sdk-core" )
  include( "dependencies/aws-cpp-sdk-s3" )
  include( "dependencies/aws-cpp-sdk-sqs" )
  include( "dependencies/aws-crt-cpp" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-auth" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-cal" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-common" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-compression" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-event-stream" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-http" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-io" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-mqtt" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-s3" )
  include( "dependencies/aws-crt-cpp/crt/aws-c-sdkutils" )
  include( "dependencies/aws-crt-cpp/crt/aws-checksums" )
  include( "dependencies/curl" )
  include( "dependencies/hiredis" )
  include( "dependencies/json-builder" )
  include( "dependencies/json-parser" )
  include( "dependencies/libparsifal" )
  include( "dependencies/librdkafka" )
  include( "dependencies/libyaml" )
  include( "dependencies/redis-plus-plus/src/sw/redis++" )
  include( "dependencies/stbrumme-hash-library" )
  include( "dependencies/zziplib" )
  include( "platform/gucefCOM" )
  include( "platform/gucefCOMCORE" )
  include( "platform/gucefCORE" )
  include( "platform/gucefIMAGE" )
  include( "platform/gucefMT" )
  include( "platform/gucefPUBSUB" )
  include( "platform/gucefVFS" )
  include( "platform/gucefWEB" )
  include( "plugins/COMCORE/comcorepluginDBL" )
  include( "plugins/COMCORE/comcorepluginGEOOSM" )
  include( "plugins/CORE/codecspluginSTBRUMMEHASH" )
  include( "plugins/CORE/codecspluginZLIB" )
  include( "plugins/CORE/dstorepluginJSONPARSER" )
  include( "plugins/CORE/dstorepluginPARSIFALXML" )
  include( "plugins/CORE/dstorepluginYAML" )
  include( "plugins/PUBSUB/pubsubpluginAWSSQS" )
  include( "plugins/PUBSUB/pubsubpluginKAFKA" )
  include( "plugins/PUBSUB/pubsubpluginREDISCLUSTER" )
  include( "plugins/PUBSUB/pubsubpluginSTORAGE" )
  include( "plugins/PUBSUB/pubsubpluginTEST" )
  include( "plugins/PUBSUB/pubsubpluginUDP" )
  include( "plugins/PUBSUB/pubsubpluginWEB" )
  include( "plugins/SHARED/pluginglueAWSSDK" )
  include( "plugins/VFS/vfspluginAWSS3" )
  include( "plugins/VFS/vfspluginZIP" )
  include( "tools/FilePusher" )
  include( "tools/FileSorter" )
  include( "tools/GucefLogServiceApp" )
  include( "tools/GucefLogServiceClientPlugin" )
  include( "tools/GucefLogServiceLib" )
  include( "tools/ProcessMetrics" )
  include( "tools/ServerPortExtender" )
  include( "tools/SocketSink" )
  include( "tools/UdpTransformer" )
  include( "tools/UdpViaTcp" )
  include( "tools/pubsub2pubsub" )
  include( "tools/pubsub2storage" )
  include( "tools/redisinfo" )
  include( "tools/udp2kafka" )
  include( "tools/udp2redis" )
  include( "tools/udp2rediscluster" )

filter "ANDROID32"

filter "ANDROID64"

filter "ARDUINO"

filter "EMSCRIPTEN32"
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )

filter "EMSCRIPTEN64"
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )

filter "IOS"

filter "LINUX32"
  include( "dependencies/FreeImage" )
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )

filter "LINUX64"
  include( "dependencies/FreeImage" )
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )

filter "OSX"

filter "WIN32"
  include( "dependencies/FreeImage" )
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/PUBSUB/pubsubpluginMSMQ" )
  include( "tools/MemoryLeakFinder" )
  include( "tools/msmqMetrics" )

filter "WIN64"
  include( "dependencies/FreeImage" )
  include( "dependencies/zlib" )
  include( "plugins/IMAGE/imgpluginFreeImage" )
  include( "plugins/PUBSUB/pubsubpluginMSMQ" )
  include( "tools/MemoryLeakFinder" )
  include( "tools/msmqMetrics" )
