--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefCORE_TestApp


project( "gucefCORE_TestApp" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "NOT WIN32" } )
  

configuration( {} )
kind( "ConsoleApp" )

configuration( {} )
links( { "gucefCORE", "gucefMT" } )
links( { "gucefCORE", "gucefMT" } )


configuration( {} )
defines( { "GUCEF_CORE_TESTAPP_BUILD_MODULE", "MODULE_CONSENSUS_NAME=gucefCORE_TestApp", "MODULE_NAME=gucefCORE_TestApp" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/TestASync.h",
  "include/TestAbstractFactory.h",
  "include/TestCronSchedule.h",
  "include/TestCyclicDynamicBuffer.h",
  "include/TestDataDrivenDStoreCodecs.h",
  "include/TestDataNodeBinarySerializer.h",
  "include/TestDateTime.h",
  "include/TestDateTimeRange.h",
  "include/TestDynamicBufferStringStream.h",
  "include/TestDynamicBufferSwap.h",
  "include/TestFileUtils.h",
  "include/TestFraction.h",
  "include/TestIniParser.h",
  "include/TestLogging.h",
  "include/TestNotifierObserver.h",
  "include/TestSchedule.h",
  "include/TestSharedPtr.h",
  "include/TestStopwatch.h",
  "include/TestString.h",
  "include/TestTimestamp.h",
  "include/TestTokenizer.h",
  "include/TestUri.h",
  "include/TestVariant.h",
  "include/TestVariantBinarySerializer.h",
  "include/TestVariantStream.h",
  "include/TestVars.h",
  "include/TestVersion.h",
  "src/TestFreeList.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/TestASync.cpp",
  "src/TestAbstractFactory.cpp",
  "src/TestCronSchedule.cpp",
  "src/TestCyclicDynamicBuffer.cpp",
  "src/TestDataDrivenDStoreCodecs.cpp",
  "src/TestDataNodeBinarySerializer.cpp",
  "src/TestDateTime.cpp",
  "src/TestDateTimeRange.cpp",
  "src/TestDynamicBufferStringStream.cpp",
  "src/TestDynamicBufferSwap.cpp",
  "src/TestFileUtils.cpp",
  "src/TestFraction.cpp",
  "src/TestFreeList.cpp",
  "src/TestIniParser.cpp",
  "src/TestLogging.cpp",
  "src/TestNotifierObserver.cpp",
  "src/TestSchedule.cpp",
  "src/TestSharedPtr.cpp",
  "src/TestStopwatch.cpp",
  "src/TestString.cpp",
  "src/TestTimestamp.cpp",
  "src/TestTokenizer.cpp",
  "src/TestUri.cpp",
  "src/TestVariant.cpp",
  "src/TestVariantBinarySerializer.cpp",
  "src/TestVariantStream.cpp",
  "src/TestVars.cpp",
  "src/TestVersion.cpp",
  "src/gucefCORE_TestApp_main.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCORE/include", "../../platform/gucefCORE/include/c_api", "../../platform/gucefMT/include", "include", "src" } )

configuration( { "ANDROID32" } )
includedirs( { "../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )
