/*
 *  ProjectGen: GUCEF module providing the business logic to generate module/project files
 *
 *  Copyright (C) 1998 - 2025.  Dinand Vanvelzen
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*-------------------------------------------------------------------------//
//                                                                         //
//      INCLUDES                                                           //
//                                                                         //
//-------------------------------------------------------------------------*/

#ifndef GUCEF_CORE_LOGGING_H
#include "gucefCORE_Logging.h"
#define GUCEF_CORE_LOGGING_H
#endif /* GUCEF_CORE_LOGGING_H ? */

#ifndef GUCEF_CORE_DVCPPFILEUTILS_H
#include "dvcppfileutils.h"
#define GUCEF_CORE_DVCPPFILEUTILS_H
#endif /* GUCEF_CORE_DVCPPFILEUTILS_H ? */

#ifndef GUCEF_CORE_DVCPPSTRINGUTILS_H
#include "dvcppstringutils.h"
#define GUCEF_CORE_DVCPPSTRINGUTILS_H
#endif /* GUCEF_CORE_DVCPPSTRINGUTILS_H ? */

#include "gucefProjectGen_CAndroidMakefileGenerator.h"

/*-------------------------------------------------------------------------//
//                                                                         //
//      NAMESPACE                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

namespace GUCEF {
namespace PROJECTGEN {

/*-------------------------------------------------------------------------//
//                                                                         //
//      GLOBAL VARS                                                        //
//                                                                         //
//-------------------------------------------------------------------------*/

const char* makefileHeader =
    "#-------------------------------------------------------------------\n"
    "# This file has been automatically generated by ProjectGenerator    \n"
    "# which is part of a build system designed for GUCEF                \n"
    "#     (Galaxy Unlimited Framework)                                  \n"
    "# For the latest info, see http://www.VanvelzenSoftware.com/        \n"
    "#                                                                   \n"
    "# The contents of this file are placed in the public domain. Feel   \n"
    "# free to make use of it in any way you like.                       \n"
    "#-------------------------------------------------------------------\n\n\n";

/*-------------------------------------------------------------------------//
//                                                                         //
//      UTILITIES                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

CORE::CString
GenerateContentForAndroidMakefile( const TModuleInfoEntryPairVector& mergeLinks ,
                                   const CModuleInfo& moduleInfo                ,
                                   const CORE::CString& moduleRoot              ,
                                   bool addGeneratorCompileTimeToOutput         ,
                                   TStringSet& ndkModulesUsed                   )
{GUCEF_TRACE;

    CORE::CString contentPrefix = makefileHeader;

    if ( addGeneratorCompileTimeToOutput )
    {
        contentPrefix +=
          "#"
          "# The project generator version used was compiled on " __TIME__ __DATE__ "\n"
          "#\n\n";
    }

    contentPrefix +=
      "ifndef MY_MODULE_PATH\n"
      "  MY_MODULE_PATH := $(call my-dir)\n"
      "endif\n"
      "LOCAL_PATH := $(MY_MODULE_PATH)\n\n"
      "include $(CLEAR_VARS)\n\n"
      "@echo Module path: $(MY_MODULE_PATH)\n"
      "LOCAL_MODULE := " + moduleInfo.name + "\n";

    if ( ( MODULETYPE_SHARED_LIBRARY == moduleInfo.moduleType ) ||
         ( MODULETYPE_STATIC_LIBRARY == moduleInfo.moduleType )  )
    {
        contentPrefix += "LOCAL_MODULE_FILENAME := lib" + moduleInfo.name + "\n";
    }
    contentPrefix += "@echo Module name: $(LOCAL_MODULE)\n\n";

    // Generate the source files section
    CORE::CString srcFilesSection = "LOCAL_SRC_FILES := \\\n";
    bool firstLoop = true;
    TStringSetMap::const_iterator i = moduleInfo.GetSourceDirs().begin();
    while ( i != moduleInfo.GetSourceDirs().end() )
    {
        const CORE::CString& srcDir = (*i).first;
        const TStringSet& srcFiles = (*i).second;

        TStringSet::const_iterator n = srcFiles.begin();
        while ( n != srcFiles.end() )
        {
            if ( !firstLoop )
            {
                srcFilesSection += " \\\n";
            }
            firstLoop = false;

            CORE::CString relFilePath = srcDir;
            CORE::AppendToPath( relFilePath, (*n) );

            srcFilesSection += "  " + relFilePath.ReplaceChar( '\\', '/' );

            ++n;
        }
        ++i;
    }

    // Add some spacing for readability
    srcFilesSection += "\n\n";

    // Generate the included files section
    // for android make files we only need the path
    // it will locate the header file on its own
    CORE::CString includeFilesSection = "LOCAL_C_INCLUDES := \\\n";
    i = moduleInfo.GetIncludeDirs().begin();
    firstLoop = true;
    while ( i != moduleInfo.GetIncludeDirs().end() )
    {
        if ( !firstLoop )
        {
            includeFilesSection += " \\\n";
        }
        firstLoop = false;

        const CORE::CString& dir = (*i).first;
        if ( !dir.IsNULLOrEmpty() )
        {
            includeFilesSection += "  $(MY_MODULE_PATH)/" + dir.ReplaceChar( '\\', '/' );
        }
        else
        {
            // Support the use-case where the include dir is empty because the moduleinfo dir == include dir
            includeFilesSection += "  $(MY_MODULE_PATH)";
        }

        ++i;
    }

    // We also need to add the include paths required to find headers
    // refered to because of dependencies
    TStringSet::const_iterator n = moduleInfo.dependencyIncludeDirs.begin();
    while ( n != moduleInfo.dependencyIncludeDirs.end() )
    {
        if ( !firstLoop )
        {
            includeFilesSection += " \\\n";
        }
        firstLoop = false;

        includeFilesSection += "  $(MY_MODULE_PATH)/" + (*n).ReplaceChar( '\\', '/' );

        ++n;
    }

    // Add some spacing for readability
    includeFilesSection += "\n\n";

    // Now we add the preprocessor definitions
    CORE::CString preprocessorSection;
    if ( !moduleInfo.preprocessorSettings.GetDefines().empty() )
    {
        preprocessorSection = "LOCAL_CFLAGS :=";

        TStringSet::const_iterator m = moduleInfo.preprocessorSettings.GetDefines().begin();
        while ( m != moduleInfo.preprocessorSettings.GetDefines().end() )
        {
            preprocessorSection += " -D" + (*m);
            ++m;
        }

        // Add some spacing for readability
        preprocessorSection += "\n\n";
    }

    // Now we add the compiler flags, if any
    // For Android we only support the GCC compilers
    CORE::CString compilerSection;
    CORE::CStringMap::const_iterator p = moduleInfo.compilerSettings.GetCompilerFlags().find( "GCC" );
    if ( p != moduleInfo.compilerSettings.GetCompilerFlags().end() )
    {
        compilerSection = "LOCAL_CFLAGS +=" + (*p).second + "\n\n";
    }
    p = moduleInfo.compilerSettings.GetCompilerFlags().find( "G++" );
    if ( p != moduleInfo.compilerSettings.GetCompilerFlags().end() )
    {
        compilerSection = "LOCAL_CPPFLAGS +=" + (*p).second + "\n\n";
    }

    // Now we will add all the dependency linking instructions.
    // For some reason it matters, at specification time, to Android's build
    // system whether the module you are linking to is a dynamically linked module
    // or a statically linked module. As such we have to figure out which is which.
    //
    // We make an alphabetical list instead of creating the section right away because
    // we don't want the order to vary in the makefile because such changes cause the NDK
    // to build the code again for no reason.
    CORE::CString linkingErrorSection;
    TStringSet linkedSharedLibraries;
    TStringSet linkedStaticLibraries;
    TStringSet linkedRuntimeLibraries;
    TLinkedLibrarySettingsPtrMap::const_iterator m = moduleInfo.linkerSettings.GetLinkedLibraries().begin();
    while ( m != moduleInfo.linkerSettings.GetLinkedLibraries().end() )
    {
        const CORE::CString& linkedLibName = (*m).first;
        TModuleType linkedLibType = (*m).second->GetModuleType();
        switch ( linkedLibType )
        {
            case MODULETYPE_EXECUTABLE:
            {
                // This is really nasty but the best option for now...
                // It is possible to link to exported symbols from an executable
                // under linux and as such we will leverage this here
                linkedSharedLibraries.insert( linkedLibName );
                break;
            }
            case MODULETYPE_SHARED_LIBRARY:
            {
                linkedSharedLibraries.insert( linkedLibName );
                break;
            }
            case MODULETYPE_STATIC_LIBRARY:
            {
                linkedStaticLibraries.insert( linkedLibName );
                break;
            }
            case MODULETYPE_CODE_INTEGRATE_LOCATION:
            case MODULETYPE_HEADER_INTEGRATE_LOCATION:
            case MODULETYPE_HEADER_INCLUDE_LOCATION:
            {
                // Skip this, no linking required
                break;
            }
            default:
            {
                // Since the dependency module type was not predefined we will investigate among
                // the other modules to try to determine the nature of the linked module
                const CModuleInfoPtr linkedDependency = FindModuleByName( mergeLinks, linkedLibName );
                if ( !linkedDependency.IsNULL() )
                {
                    // The module we are linking too is part of this project.
                    // As such we can simply check the other module's info
                    // to find out whether its a dynamically linked module or not
                    // which in turn tells us how to instruct the Android build system
                    // to link.
                    switch( linkedDependency->moduleType )
                    {
                        case MODULETYPE_SHARED_LIBRARY:
                        {
                            linkedSharedLibraries.insert( linkedLibName );
                            break;
                        }
                        case MODULETYPE_STATIC_LIBRARY:
                        {
                            linkedStaticLibraries.insert( linkedLibName );
                            break;
                        }
                        case MODULETYPE_EXECUTABLE:
                        {
                            // This is really nasty but the best option for now...
                            // It is possible to link to exported symbols from an executable
                            // under linux and as such we will leverage this here
                            linkedSharedLibraries.insert( linkedLibName );
                            break;
                        }
                        case MODULETYPE_HEADER_INTEGRATE_LOCATION:
                        case MODULETYPE_CODE_INTEGRATE_LOCATION:
                        {
                            // Dont do anything.
                            // The files for this 'module' have already been merged into the dependent module
                            break;
                        }
                        case MODULETYPE_HEADER_INCLUDE_LOCATION:
                        {
                            // Don't have to do anything.
                            // Due to the auto-dependency tracking of include paths the header paths will have been added to
                            // whatever module depends on this 'module'
                            break;
                        }
                        default:
                        {
                            linkingErrorSection +=
                              "# *** ERROR *** Finish me\n"
                              "# Unable to determine module type from the source information\n"
                              "# Please edit the line below to manually set the correct linking method for this dependency\n";
                            linkingErrorSection += "#LOCAL_<(LDLIBS???)> += " + moduleInfo.name + "\n\n";

                            GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Error: the module " + moduleInfo.name + " does not have a useable module type set, you will have to manually edit the file to correct the error" );
                            break;
                        }
                    }
                }
                else
                {
                    // If we get here then this dependency is not on a module which is part of the project
                    // As such we cannot build this module thus the only appropriate linking method would seem
                    // to be the one where we simply instruct the linker to load this dependency at runtime.
                    // This will typically be the case for any Android NDK modules we have to link to.
                    linkedRuntimeLibraries.insert( linkedLibName );
                }
            }
        }
        ++m;
    }

    CORE::CString linkingSection;
    CORE::CString linkedSharedLibrariesSection = "\nLOCAL_SHARED_LIBRARIES := \\\n";
    CORE::CString linkedStaticLibrariesSection = "\nLOCAL_STATIC_LIBRARIES := \\\n";
    CORE::CString linkedRuntimeLibrariesSection = "\nLOCAL_LDLIBS := \\\n";

    // Based on what was found we will construct the linking section
    bool first = true;
    n = linkedSharedLibraries.begin();
    while ( n != linkedSharedLibraries.end() )
    {
        if ( !first )
        {
             linkedSharedLibrariesSection += " \\\n";
        }
        linkedSharedLibrariesSection += "  " + (*n);
        first = false;
        ++n;
    }
    first = true;
    n = linkedStaticLibraries.begin();
    while ( n != linkedStaticLibraries.end() )
    {
        if ( !first )
        {
             linkedStaticLibrariesSection += " \\\n";
        }
        linkedStaticLibrariesSection += "  " + (*n);
        first = false;
        ++n;
    }
    first = true;
    n = linkedRuntimeLibraries.begin();
    while ( n != linkedRuntimeLibraries.end() )
    {
        if ( !first )
        {
             linkedRuntimeLibrariesSection += " \\\n";
        }
        linkedRuntimeLibrariesSection += "  -l" + (*n);
        first = false;
        ++n;
    }

    if ( !linkedSharedLibraries.empty() )
    {
        linkingSection += linkedSharedLibrariesSection + "\n\n";
    }
    if ( !linkedStaticLibraries.empty() )
    {
        linkingSection += linkedStaticLibrariesSection + "\n\n";
    }
    if ( !linkedRuntimeLibraries.empty() )
    {
        linkingSection += linkedRuntimeLibrariesSection + "\n\n";
    }
    linkingSection += linkingErrorSection;

    // Check if we have a file on disk of information which is to be inserted into
    // our automatically generated make file
    CORE::CString manualContent;
    CORE::CString manualContentFilePath = moduleRoot;
    CORE::AppendToPath( manualContentFilePath, "AndroidAddition.mk" );
    if ( CORE::FileExists( manualContentFilePath ) )
    {
        if ( CORE::LoadTextFileAsString( manualContentFilePath ,
                                         manualContent         ) )
        {
            GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Successfully loaded manually defined content for module " + moduleInfo.name + " from addition file " + manualContentFilePath );
        }
        else
        {
            manualContent =
              "# *** ERROR *** Finish me\n"
              "# Unable to load manually defined content from detected AndroidAddition.mk file\n"
              "# Please manually insert its contents here\n\n";
            GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Error: the module " + moduleInfo.name + " has manually defined content in a AndroidAddition.mk file but it could not be loaded, you will have to manually edit the file to correct the error" );
        }
    }

    // Now generate the latter part of the file which contains more meta data about the module
    CORE::CString contentSuffix;
    switch ( moduleInfo.moduleType )
    {
        case MODULETYPE_SHARED_LIBRARY:
        {
            contentSuffix += "include $(BUILD_SHARED_LIBRARY)\n\n";
            break;
        }
        case MODULETYPE_STATIC_LIBRARY:
        {
            contentSuffix += "include $(BUILD_STATIC_LIBRARY)\n\n";
            break;
        }
        case MODULETYPE_EXECUTABLE:
        {
            contentSuffix += "include $(BUILD_EXECUTABLE)\n\n";
            break;
        }
        default:
        {
            contentSuffix +=
              "# *** ERROR *** Finish me\n"
              "# Unable to determine module type from the source information\n"
              "# Please edit the line below to manually set the correct module type to build\n"
              "#include $(BUILD_???)\n\n";

            GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Error: the module " + moduleInfo.name + " does not have a useable module type set, you will have to manually edit the file to correct the error" );
            break;
        }
    }

    // Check for NDK static libraries to import
    if ( !linkedStaticLibraries.empty() )
    {
        TStringSet::iterator a = linkedStaticLibraries.find( "android_native_app_glue" );
        if ( a != linkedStaticLibraries.end() )
        {
            ndkModulesUsed.insert( "android_native_app_glue" );
            contentSuffix += "$(call import-module,android/native_app_glue)\n";
        }
        a = linkedStaticLibraries.find( "cpufeatures" );
        if ( a != linkedStaticLibraries.end() )
        {
            ndkModulesUsed.insert( "cpufeatures" );
            contentSuffix += "$(call import-module,android/cpufeatures)\n";
        }
    }

    return contentPrefix + srcFilesSection + includeFilesSection + preprocessorSection + compilerSection + linkingSection + manualContent + contentSuffix;
}

/*-------------------------------------------------------------------------*/

bool
DidMakefileContentChange( const CORE::CString& makefilePath ,
                          const CORE::CString& newContent   )
{GUCEF_TRACE;

    CORE::CString preexistingContent;
    if ( CORE::LoadTextFileAsString( makefilePath, preexistingContent ) )
    {
        GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Found a pre-existing Android makefile at " + makefilePath + ", comparing against new content..." );

        if ( newContent == preexistingContent )
        {
            return false;
        }
    }
    return true;
}

/*-------------------------------------------------------------------------*/

bool
CreateAndroidMakefileOnDiskForModule( const TModuleInfoEntryPairVector& mergeLinks ,
                                      const CModuleInfo& moduleInfo                ,
                                      const CORE::CString& moduleRoot              ,
                                      bool addGeneratorCompileTimeToOutput         ,
                                      TStringSet& ndkModulesUsed                   )
{GUCEF_TRACE;

    if ( ( MODULETYPE_HEADER_INCLUDE_LOCATION == moduleInfo.moduleType )   ||
         ( MODULETYPE_HEADER_INTEGRATE_LOCATION == moduleInfo.moduleType ) ||
         ( MODULETYPE_CODE_INTEGRATE_LOCATION == moduleInfo.moduleType )    )
    {
        // this module type does not require processing here
        return true;
    }

    GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Generating Android makefile content for module " + moduleInfo.name );

    // First we generate the content for the makefile based on the given module information
    CORE::CString makefileContent = GenerateContentForAndroidMakefile( mergeLinks                      ,
                                                                       moduleInfo                      ,
                                                                       moduleRoot                      ,
                                                                       addGeneratorCompileTimeToOutput ,
                                                                       ndkModulesUsed                  );

    // Now we write the makefile to the root location of the module since everything is relative to that
    CORE::CString makefilePath = moduleRoot;
    CORE::AppendToPath( makefilePath, "Android.mk" );

    // Do not change the file on disk unless we have to.
    // the NDK build system will rebuild if the timestamp on the file changed which can take a long time
    if ( DidMakefileContentChange( makefilePath, makefileContent ) )
    {
        GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Writing Android makefile content for module " + moduleInfo.name + " to " + makefilePath );

        if ( CORE::WriteStringAsTextFile( makefilePath    ,
                                          makefileContent ,
                                          true            ,
                                          "\n"            ) )
        {
            GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Successfully created Android makefile for module " + moduleInfo.name + " at " + makefilePath );
            return true;
        }
        GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Failed to create an Android makefile for module " + moduleInfo.name + " at " + makefilePath );
        return false;
    }
    else
    {
        GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Skipping creation of Android makefile for module " + moduleInfo.name + " at " + makefilePath +
            " since there already is a makefile with identical content" );
        return true;
    }
}

/*-------------------------------------------------------------------------*/

bool
CreateAndroidMakefileOnDiskForEachModule( const TModuleInfoEntryPairVector& mergeLinks ,
                                          bool addGeneratorCompileTimeToOutput         ,
                                          TStringSet& ndkModulesUsed                   )
{GUCEF_TRACE;

    TModuleInfoEntryPairVector::const_iterator i = mergeLinks.begin();
    while ( i != mergeLinks.end() )
    {
        const CModuleInfoEntry& moduleInfoEntry = (*(*i).first);
        const CModuleInfo& moduleInfo = (*(*i).second);

        if ( !CreateAndroidMakefileOnDiskForModule( mergeLinks                      ,
                                                    moduleInfo                      ,
                                                    moduleInfoEntry.rootDir         ,
                                                    addGeneratorCompileTimeToOutput ,
                                                    ndkModulesUsed                  ) )
        {
            GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Failed to create an Android makefile for all modules because of the following module " + moduleInfo.name );
            return false;
        }

        ++i;
    }
    return true;
}

/*-------------------------------------------------------------------------*/

const CModuleInfoPtr
FindFirstModuleAccordingToBuildOrder( const TModuleInfoEntryPairVector& mergeLinks )
{GUCEF_TRACE;

    Int64 actualLowestBuildOrderFound = GUCEFCORE_INT32MAX;
    CModuleInfoPtr candidateModule;

    TModuleInfoEntryPairVector::const_iterator i = mergeLinks.begin();
    while ( i != mergeLinks.end() )
    {
        Int64 candidateBuildOrder = (*i).second->buildOrder;
        if ( candidateBuildOrder < actualLowestBuildOrderFound )
        {
            candidateModule = (*i).second;
            actualLowestBuildOrderFound = candidateBuildOrder;
        }
        ++i;
    }
    return candidateModule;
}

/*-------------------------------------------------------------------------*/

const CModuleInfoPtr
FindNextModuleAccordingToBuildOrder( const TModuleInfoEntryPairVector& mergeLinks ,
                                     const CModuleInfoPtr& currentModule          )
{GUCEF_TRACE;

    Int64 lowestAllowedModuleBuildOrder = currentModule->buildOrder+1;
    Int64 actualLowestBuildOrderFound = GUCEF_INT64MAX;
    CModuleInfoPtr candidateModule;

    TModuleInfoEntryPairVector::const_iterator i = mergeLinks.begin();
    while ( i != mergeLinks.end() )
    {
        Int64 candidateBuildOrder = (*i).second->buildOrder;
        if ( candidateBuildOrder >= lowestAllowedModuleBuildOrder && 
             candidateBuildOrder < actualLowestBuildOrderFound     )
        {
            candidateModule = (*i).second;
            actualLowestBuildOrderFound = candidateBuildOrder;
        }
        ++i;
    }
    return candidateModule;
}

/*-------------------------------------------------------------------------*/

const CModuleInfoEntryPtr
FindModuleInfoEntryForMergedInfo( const TModuleInfoEntryPairVector& mergeLinks ,
                                  const CModuleInfoPtr& mergedModule           )
{
    TModuleInfoEntryPairVector::const_iterator i = mergeLinks.begin();
    while ( i != mergeLinks.end() )
    {
        if ( (*i).second.GetPointerAlways() == mergedModule.GetPointerAlways() && !mergedModule.IsNULL() )
        {
            return (*i).first;
        }
        ++i;
    }
    return CModuleInfoEntryPtr();
}

/*-------------------------------------------------------------------------*/

CORE::CString
GenerateContentForAndroidProjectMakefile( const CORE::CString& projectName             ,
                                          const TModuleInfoEntryPairVector& mergeLinks ,
                                          const CORE::CString& outputDir               ,
                                          bool addGeneratorCompileTimeToOutput         ,
                                          const TStringSet& ndkModulesUsed             )
{GUCEF_TRACE;

    GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Generating Android makefile content for overall project file regarding project \"" + projectName + "\"" );

    CORE::CString contentPrefix = makefileHeader;

    contentPrefix +=
      "#\n"
      "# This is the project makefile which includes all modules which are part of this project\n"
      "#\n";

    contentPrefix +=
      "# PROJECT: \"" + projectName + "\"\n#\n\n";

    if ( addGeneratorCompileTimeToOutput )
    {
        contentPrefix +=
          "#"
          "# The project generator version used was compiled on " __TIME__ __DATE__ "\n"
          "#\n\n";
    }

    contentPrefix +=
      "ifndef PROJECT_ROOT_PATH\n"
      "  PROJECT_ROOT_PATH := $(call my-dir)\n"
      "endif\n\n"
      "include $(CLEAR_VARS)\n\n";

    // Include makefiles for NDK modules used
    CORE::CString moduleListSection;

/* ->  Not needed
    if ( !ndkModulesUsed.empty() )
    {
        TStringSet::iterator i = ndkModulesUsed.find( "android_native_app_glue" );
        if ( i != ndkModulesUsed.end() ) 
        {
            moduleListSection += "MY_MODULE_PATH := $(ANDROIDNDK)/sources/android/native_app_glue\n";
            moduleListSection += "include $(MY_MODULE_PATH)/Android.mk\n\n";
        }
        i = ndkModulesUsed.find( "cpufeatures" );
        if ( i != ndkModulesUsed.end() ) 
        {
            moduleListSection += "MY_MODULE_PATH := $(ANDROIDNDK)/sources/android/cpufeatures\n";
            moduleListSection += "include $(MY_MODULE_PATH)/Android.mk\n\n";
        }
    }
*/
    // Include each module's makefile in the order listed as their build order
    CModuleInfoPtr currentModule = FindFirstModuleAccordingToBuildOrder( mergeLinks );
    while ( !currentModule.IsNULL() )
    {
        if ( ( MODULETYPE_HEADER_INCLUDE_LOCATION != currentModule->moduleType )   &&
             ( MODULETYPE_HEADER_INTEGRATE_LOCATION != currentModule->moduleType ) &&
             ( MODULETYPE_CODE_INTEGRATE_LOCATION != currentModule->moduleType )    )
        {
            // Get relative path from the outputDir to the other module
            const CModuleInfoEntryPtr fullModuleInfo = FindModuleInfoEntryForMergedInfo( mergeLinks, currentModule );
            CORE::CString relativePathToModule = CORE::GetRelativePathToOtherPathRoot( outputDir, fullModuleInfo->rootDir );
            relativePathToModule = relativePathToModule.ReplaceChar( '\\', '/' );

            // Add entry for this module to the project file
            moduleListSection += "MY_MODULE_PATH := $(PROJECT_ROOT_PATH)/" + relativePathToModule + "\n";
            moduleListSection += "include $(MY_MODULE_PATH)/Android.mk\n\n";
        }

        // Done with this module, go to the next one
        currentModule = FindNextModuleAccordingToBuildOrder( mergeLinks, currentModule );
    }

    return contentPrefix + moduleListSection;
}

/*-------------------------------------------------------------------------*/

bool
CreateAndroidProjectMakefileOnDisk( const CORE::CString& projectName             ,
                                    const TModuleInfoEntryPairVector& mergeLinks ,
                                    const CORE::CString& outputDir               ,
                                    bool addGeneratorCompileTimeToOutput         ,
                                    const TStringSet& ndkModulesUsed             )
{GUCEF_TRACE;

    GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Generating Android makefile content for overall project file regarding project \"" + projectName + "\"" );

    // First we generate the content for the makefile based on the given module information
    CORE::CString makefileContent = GenerateContentForAndroidProjectMakefile( projectName                     ,
                                                                              mergeLinks                      ,
                                                                              outputDir                       ,
                                                                              addGeneratorCompileTimeToOutput ,
                                                                              ndkModulesUsed                  );

    // Now we write the makefile to the root location of the project since everything is relative to that
    CORE::CString makefilePath = CORE::CombinePath( outputDir, "Android.mk" );

    // Do not change the file on disk unless we have to.
    // the NDK build system will rebuild if the timestamp on the file changed which can take a long time
    if ( DidMakefileContentChange( makefilePath, makefileContent ) )
    {
        GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Writing Android makefile content for project \"" + projectName + "\" to " + makefilePath );

        if ( CORE::WriteStringAsTextFile( makefilePath    ,
                                          makefileContent ,
                                          true            ,
                                          "\n"            ) )
        {
            GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Successfully created Android makefile for project \"" + projectName + "\" at " + makefilePath );
            return true;
        }
        GUCEF_ERROR_LOG( CORE::LOGLEVEL_NORMAL, "Failed to create an Android makefile for project \"" + projectName + "\" at " + makefilePath );
        return false;
    }
    else
    {
        GUCEF_LOG( CORE::LOGLEVEL_NORMAL, "Skipping creation of overall project Android makefile for project \"" + projectName + "\" at " + makefilePath +
            " since there already is a makefile with identical content" );
        return true;
    }
}

/*--------------------------------------------------------------------------*/

void
WriteAndroidTargetsToDisk( const CProjectInfo& projectInfo          ,
                           const CORE::CString& projectName         ,
                           const CORE::CString& targetName          ,
                           const TProjectTargetInfo& targetInfo     ,
                           const CORE::CString& outputDir           ,
                           const CORE::CString& targetsOutputDir    ,
                           bool addCompileDate                      ,
                           const TStringSet& ndkModulesUsed         )
{GUCEF_TRACE;

    // Merge all the module info to give us a complete module definition for the Android platform
    // per module. This makes is easy for us to process as we don't care about other platforms
    TModuleInfoPtrVector mergedInfo;
    TModuleInfoEntryPairVector mergeLinks;
    MergeAllModuleInfoForPlatform( targetInfo.modules, "android", mergedInfo, mergeLinks ); 

    CORE::CString targetOutputDir = CORE::CombinePath( targetsOutputDir, projectName );
    if ( CORE::CreateDirs( targetOutputDir ) )
    {
        // Now we can create the overall project file which refers to each of the make files
        // we just created per module.
        CreateAndroidProjectMakefileOnDisk( projectName     ,
                                            mergeLinks      ,
                                            targetOutputDir ,
                                            addCompileDate  ,
                                            ndkModulesUsed  );
    }
    else
    {
        GUCEF_ERROR_LOG( CORE::LOGLEVEL_IMPORTANT, "WriteAndroidTargetsToDisk: Failed to create Android project target output folder: " + targetOutputDir );
    }
}

/*--------------------------------------------------------------------------*/

void
WriteAndroidTargetsToDisk( const CProjectInfo& projectInfo         ,
                           const TProjectTargetInfoMapMap& targets ,
                           const CORE::CString& outputDir          ,
                           const CORE::CString& targetsOutputDir   ,
                           bool addCompileDate                     ,
                           bool splitAndroidTargets                ,
                           const TStringSet& ndkModulesUsed        )
{GUCEF_TRACE;

    if ( splitAndroidTargets )
    {
        TProjectTargetInfoMapMap::const_iterator t = targets.begin();
        while ( t != targets.end() )
        {
            const CORE::CString& projectName = (*t).first;

            CORE::CString targetName = GetConsensusTargetName( (*t).second, "android" );
            if ( targetName.IsNULLOrEmpty() )
                targetName = projectName;
            
            const TProjectTargetInfo* projectTargetInfo = GetPlatformProjectTarget( (*t).second, "android" );
            if ( GUCEF_NULL != projectTargetInfo )
            {
                WriteAndroidTargetsToDisk( projectInfo        ,
                                           projectName        ,
                                           targetName         ,
                                           *projectTargetInfo ,   
                                           outputDir          ,
                                           targetsOutputDir   ,
                                           addCompileDate     ,
                                           ndkModulesUsed     );
            }
            ++t;
        }
    }
    else
    {
        TProjectTargetInfoMapMap::const_iterator t = targets.find( projectInfo.projectName );
        if ( t != targets.end() )
        {
            const TProjectTargetInfo* projectTargetInfo = GetPlatformProjectTarget( (*t).second, "all" );
            if ( GUCEF_NULL != projectTargetInfo )
            {
                WriteAndroidTargetsToDisk( projectInfo             ,
                                           projectInfo.projectName ,
                                           projectInfo.projectName ,
                                           *projectTargetInfo      ,
                                           outputDir               ,
                                           outputDir               ,
                                           addCompileDate          ,
                                           ndkModulesUsed          );
            }
        }
    }
}

/*-------------------------------------------------------------------------*/

CAndroidMakefileGenerator::CAndroidMakefileGenerator( void )
{GUCEF_TRACE;

}

/*-------------------------------------------------------------------------*/

CAndroidMakefileGenerator::~CAndroidMakefileGenerator()
{GUCEF_TRACE;

}

/*-------------------------------------------------------------------------*/

bool
CAndroidMakefileGenerator::GenerateProject( const CProjectInfo& projectInfo      ,
                                            const CORE::CString& outputDir       ,
                                            bool addGeneratorCompileTimeToOutput ,
                                            const CORE::CValueList& params       )
{GUCEF_TRACE;

    bool treatTagsAsTargets = CORE::StringToBool( params.GetValueAlways( "TreatTagsAsTargets" ), true );
    bool splitTargets = CORE::StringToBool( params.GetValueAlways( "androidmakegen:SplitTargets" ), true );

    CORE::CString targetsOutputDir = params.GetValueAlways( "androidmakegen:TargetsDir" ).AsString( CORE::CString::Empty, true );
    if ( targetsOutputDir.IsNULLOrEmpty() )
        targetsOutputDir = outputDir;    
    targetsOutputDir = CORE::RelativePath( targetsOutputDir, true );
    if ( !CORE::CreateDirs( targetsOutputDir ) )
        GUCEF_ERROR_LOG( CORE::LOGLEVEL_IMPORTANT, "Failed to create Android project targets output folder: " + targetsOutputDir );

    // Merge all the module info to give us a complete module definition for the Android platform
    // per module. This makes is easy for us to process as we don't care about other platforms
    TModuleInfoPtrVector mergedInfo;
    TModuleInfoEntryPairVector mergeLinks;
    MergeAllModuleInfoForPlatform( projectInfo.modules, "android", mergedInfo, mergeLinks ); 

    // First we create a makefile per module on disk
    TStringSet ndkModulesUsed;
    if ( CreateAndroidMakefileOnDiskForEachModule( mergeLinks                      ,
                                                   addGeneratorCompileTimeToOutput ,
                                                   ndkModulesUsed                  ) )
    {
        // Now we can create the overall project files per target which refer to each of the make files
        // we just created per module.

        TStringSet platformsUsed;
        platformsUsed.insert( "android" );
        TProjectTargetInfoMapMap targets;
        SplitProjectPerTarget( projectInfo, targets, treatTagsAsTargets, true, platformsUsed );

        WriteAndroidTargetsToDisk( projectInfo                     ,
                                   targets                         ,
                                   outputDir                       ,
                                   targetsOutputDir                ,
                                   addGeneratorCompileTimeToOutput ,
                                   splitTargets                    ,
                                   ndkModulesUsed                  );
    
        return true;
    }
    return false;
}

/*-------------------------------------------------------------------------//
//                                                                         //
//      NAMESPACE                                                          //
//                                                                         //
//-------------------------------------------------------------------------*/

}; /* namespace PROJECTGEN */
}; /* namespace GUCEF */

/*-------------------------------------------------------------------------*/
