--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefDRN_TestApp


configuration( { "LINUX32" } )
  project( "gucefDRN_TestApp" )

configuration( { "LINUX64" } )
  project( "gucefDRN_TestApp" )

configuration( { "WIN32" } )
  project( "gucefDRN_TestApp" )

configuration( { "WIN64" } )
  project( "gucefDRN_TestApp" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "LINUX32" } )
language( "C++" )

configuration( { "LINUX64" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "LINUX32" } )


configuration( { LINUX32 } )
kind( "ConsoleApp" )
configuration( { "LINUX64" } )


configuration( { LINUX64 } )
kind( "ConsoleApp" )
configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "WindowedApp" )
  
configuration( { LINUX32 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  

configuration( { LINUX32 } )
defines( { "GUCEF_DRN_TESTAPP_BUILD_MODULE", "MODULE_NAME=gucefDRN_TestApp" } )
  
configuration( { LINUX64 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  

configuration( { LINUX64 } )
defines( { "GUCEF_DRN_TESTAPP_BUILD_MODULE", "MODULE_NAME=gucefDRN_TestApp" } )
  
configuration( { WIN32 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_DRN_TESTAPP_BUILD_MODULE", "MODULE_NAME=gucefDRN_TestApp" } )
  
configuration( { WIN64 } )
links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  links( { "gucefCOMCORE", "gucefCORE", "gucefDRN", "gucefMT" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_DRN_TESTAPP_BUILD_MODULE", "MODULE_NAME=gucefDRN_TestApp" } )


configuration( { "LINUX32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCode_PeerToPeer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/TestCode_PeerToPeer.cpp",
      "src/gucefDRN_TestApp.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCode_PeerToPeer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/TestCode_PeerToPeer.cpp",
      "src/gucefDRN_TestApp.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCode_PeerToPeer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/TestCode_PeerToPeer.cpp",
      "src/gucefDRN_TestApp.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCode_PeerToPeer.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/TestCode_PeerToPeer.cpp",
      "src/gucefDRN_TestApp.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCOMCORE/include", "../../platform/gucefCORE/include", "../../platform/gucefCORE/include/c_api", "../../platform/gucefDRN/include", "../../platform/gucefMT/include" } )

configuration( { "LINUX32" } )
includedirs( { "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux", "include" } )

configuration( { "LINUX64" } )
includedirs( { "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux", "include" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin", "include" } )
