apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: statsite
 name: statsite
spec:
 replicas: 1
 selector:
   matchLabels:
     app: statsite
 template:
   metadata:
     labels:
       app: statsite
   spec:
     containers:
     - image: statsite/statsite
       name: statsite
       ports:
       - containerPort: 8125
         name: statsd
---
apiVersion: v1
kind: Service
metadata:
 name: statsite-udp
 labels:
   app: statsite
spec:
 type: LoadBalancer
 ports:
 - port: 8125
   protocol: UDP
   targetPort: 8125
   name: statsd-udp
 selector:
   app: statsite
---
apiVersion: v1
kind: Service
metadata:
 name: statsite-tcp
 labels:
   app: statsite
spec:
 type: LoadBalancer
 ports:
 - port: 8126
   protocol: TCP
   targetPort: 8125
   name: statsd-tcp
 selector:
   app: statsite
