--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: codecspluginSTBRUMMEHASH


project( "codecspluginSTBRUMMEHASH" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "stbrumme-hash" } )
links( { "stbrumme-hash" } )


configuration( {} )
defines( { "GUCEF_CODECPLUGIN_BUILD_MODULE", "MODULE_CONSENSUS_NAME=codecspluginSTBRUMMEHASH", "MODULE_IS_PLUGIN=1", "MODULE_NAME=codecspluginSTBRUMMEHASH" } )
  

configuration( { EMSCRIPTEN32 } )
defines( { "MODULE_API_PREFIX=codecspluginSTBRUMMEHASH" } )
  

configuration( { EMSCRIPTEN64 } )
defines( { "MODULE_API_PREFIX=codecspluginSTBRUMMEHASH" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/codecspluginSTBRUMMEHASH.h",
  "include/codecspluginSTBRUMMEHASH_config.h",
  "include/codecspluginSTBRUMMEHASH_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/codecspluginSTBRUMMEHASH.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/stbrumme-hash-library", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
