--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MemoryLeakFinder_TestApp


configuration( { "WIN32" } )
  project( "MemoryLeakFinder_TestApp" )

configuration( { "WIN64" } )
  project( "MemoryLeakFinder_TestApp" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "WindowedApp" )
  
configuration( { WIN32 } )
links( { "MemoryLeakFinder", "gucefCORE", "gucefMT" } )
  links( { "gucefCORE", "gucefMT" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_DRGUP_TESTAPP_BUILD_MODULE", "MEMCHECK_OLEAPI", "MODULE_NAME=MemoryLeakFinder_TestApp" } )
  
configuration( { WIN64 } )
links( { "MemoryLeakFinder", "gucefCORE", "gucefMT" } )
  links( { "gucefCORE", "gucefMT" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_DRGUP_TESTAPP_BUILD_MODULE", "MEMCHECK_OLEAPI", "MODULE_NAME=MemoryLeakFinder_TestApp" } )


configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCallStack.h",
      "include/TestConfig.h",
      "include/TestLockTracer.h",
      "include/TestMemoryTracking.h",
      "include/TestOleApi.h",
      "include/TestReporter.h",
      "include/TestSentinels.h",
      "include/TestStatistics.h",
      "include/TestTrackerLifecycle.h",
      "include/TestValidation.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryLeakFinder_TestApp_main.cpp",
      "src/TestCallStack.cpp",
      "src/TestConfig.cpp",
      "src/TestLockTracer.cpp",
      "src/TestMemoryTracking.cpp",
      "src/TestOleApi.cpp",
      "src/TestReporter.cpp",
      "src/TestSentinels.cpp",
      "src/TestStatistics.cpp",
      "src/TestTrackerLifecycle.cpp",
      "src/TestValidation.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "include/TestCallStack.h",
      "include/TestConfig.h",
      "include/TestLockTracer.h",
      "include/TestMemoryTracking.h",
      "include/TestOleApi.h",
      "include/TestReporter.h",
      "include/TestSentinels.h",
      "include/TestStatistics.h",
      "include/TestTrackerLifecycle.h",
      "include/TestValidation.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "src/MemoryLeakFinder_TestApp_main.cpp",
      "src/TestCallStack.cpp",
      "src/TestConfig.cpp",
      "src/TestLockTracer.cpp",
      "src/TestMemoryTracking.cpp",
      "src/TestOleApi.cpp",
      "src/TestReporter.cpp",
      "src/TestSentinels.cpp",
      "src/TestStatistics.cpp",
      "src/TestTrackerLifecycle.cpp",
      "src/TestValidation.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCORE/include", "../../platform/gucefCORE/include/c_api", "../../platform/gucefMT/include" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin", "../../platform/gucefMT/include/mswin/", "../../tools/MemoryLeakFinder/include", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin", "../../platform/gucefMT/include/mswin/", "../../tools/MemoryLeakFinder/include", "include" } )
