--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: codecspluginZLIB


project( "codecspluginZLIB" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "zlib" } )


configuration( {} )
defines( { "GUCEF_CODECPLUGIN_BUILD_MODULE", "MODULE_CONSENSUS_NAME=codecspluginZLIB", "MODULE_IS_PLUGIN=1", "MODULE_NAME=codecspluginZLIB" } )
  links( { "z" } )
  links( { "z" } )
  

configuration( { EMSCRIPTEN32 } )
defines( { "MODULE_API_PREFIX=codecspluginZLIB" } )
  

configuration( { EMSCRIPTEN64 } )
defines( { "MODULE_API_PREFIX=codecspluginZLIB" } )
  
configuration( { LINUX32 } )
links( { "zlib" } )
  links( { "zlib" } )
  
configuration( { LINUX64 } )
links( { "zlib" } )
  links( { "zlib" } )
  
configuration( { WIN32 } )
links( { "zlib" } )
  links( { "zlib" } )
  
configuration( { WIN64 } )
links( { "zlib" } )
  links( { "zlib" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/codecspluginZLIB.h",
  "include/codecspluginZLIB_config.h",
  "include/codecspluginZLIB_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/codecspluginZLIB.c"
 } )


configuration( {} )
includedirs( { "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../../dependencies/zlib" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../../dependencies/zlib" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
