--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_exe_gucefPATCHERAPP_TestApp" )

  platforms( { "ALL", "ANDROID32", "ANDROID64", "ARDUINO", "EMSCRIPTEN32", "EMSCRIPTEN64", "IOS", "LINUX32", "LINUX64", "OSX", "WIN32", "WIN64" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "ANDROID32"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "ANDROID64"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "ARDUINO"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "EMSCRIPTEN32"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "EMSCRIPTEN64"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "IOS"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "LINUX32"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "LINUX64"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "OSX"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "WIN32"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )

filter "WIN64"
  include( "platform/gucefCORE" )
  include( "platform/gucefLOADER" )
  include( "platform/gucefMT" )
  include( "tests/gucefPATCHERAPP_TestApp" )
