--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: RmlUI_Debugger


project( "RmlUI_Debugger" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "RmlUI_Core", "freetype" } )
links( { "RmlUI_Core", "freetype" } )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=RmlUI_Debugger", "MODULE_NAME=RmlUI_Debugger" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "BeaconSource.h",
  "CommonSource.h",
  "DataModelsSource.h",
  "DebuggerPlugin.h",
  "DebuggerSystemInterface.h",
  "ElementContextHook.h",
  "ElementDataModels.h",
  "ElementDebugDocument.h",
  "ElementInfo.h",
  "ElementLog.h",
  "FontSource.h",
  "Geometry.h",
  "InfoSource.h",
  "LogSource.h",
  "MenuSource.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "Debugger.cpp",
  "DebuggerPlugin.cpp",
  "DebuggerSystemInterface.cpp",
  "ElementContextHook.cpp",
  "ElementDataModels.cpp",
  "ElementDebugDocument.cpp",
  "ElementInfo.cpp",
  "ElementLog.cpp",
  "Geometry.cpp"
 } )


configuration( {} )
includedirs( { "../../../freetype/include", "../../../freetype/include/freetype", "../../../freetype/include/freetype/config", "../../../freetype/include/freetype/internal", "../../../freetype/include/freetype/internal/services", "../../../freetype/src", "../../../freetype/src/winfonts", "../../Include", "../../Include/RmlUi", "../../Include/RmlUi/Config", "../../Include/RmlUi/Core", "../../Include/RmlUi/Core/Containers", "../../Include/RmlUi/Core/Containers/itlib", "../../Include/RmlUi/Core/Elements", "../../Include/RmlUi/Debugger", "../../Include/RmlUi/Lottie", "../../Include/RmlUi/Lua", "../../Include/RmlUi/SVG", "../Core", "../Core/Elements", "../Core/FontEngineDefault", "../Core/Layout" } )
