--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: udp2rediscluster


project( "udp2rediscluster" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "NOT WIN32" } )
  

configuration( {} )
kind( "ConsoleApp" )

configuration( {} )
links( { "gucefCOM", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefWEB", "hiredis", "redis-plus-plus" } )
links( { "gucefCOM", "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefWEB", "hiredis", "redis-plus-plus" } )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=udp2rediscluster", "MODULE_NAME=udp2rediscluster" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/crc16.h",
  "include/udp2rediscluster.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/crc16.cpp",
  "src/main.cpp",
  "src/udp2rediscluster.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../../dependencies/", "../../dependencies/hiredis", "../../dependencies/redis-plus-plus/src/", "../../dependencies/redis-plus-plus/src/sw/redis++", "../../dependencies/redis-plus-plus/src/sw/redis++/cxx11", "../../dependencies/redis-plus-plus/src/sw/redis++/cxx11/sw", "../../dependencies/redis-plus-plus/src/sw/redis++/cxx11/sw/redis++", "../../dependencies/redis-plus-plus/src/sw/redis++/no_tls", "../../dependencies/redis-plus-plus/src/sw/redis++/no_tls/sw", "../../dependencies/redis-plus-plus/src/sw/redis++/no_tls/sw/redis++", "../../dependencies/redis-plus-plus/src/sw/redis++/patterns", "../../platform/gucefCOM/include", "../../platform/gucefCOMCORE/include", "../../platform/gucefCORE/include", "../../platform/gucefCORE/include/c_api", "../../platform/gucefMT/include", "../../platform/gucefVFS/include", "../../platform/gucefWEB/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCORE/include/android" } )

configuration( { "ARDUINO" } )
includedirs( { "../../dependencies/hiredis" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../dependencies/hiredis" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../dependencies/hiredis" } )

configuration( { "IOS" } )
includedirs( { "../../dependencies/hiredis" } )

configuration( { "LINUX32" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux" } )

configuration( { "OSX" } )
includedirs( { "../../dependencies/hiredis" } )

configuration( { "WIN32" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../dependencies/hiredis", "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )
