#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := aws-cpp-sdk-sns
LOCAL_MODULE_FILENAME := libaws-cpp-sdk-sns
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  source/SNSClient.cpp \
  source/SNSEndpointProvider.cpp \
  source/SNSEndpointRules.cpp \
  source/SNSErrorMarshaller.cpp \
  source/SNSErrors.cpp \
  source/SNSRequest.cpp \
  source/model/AddPermissionRequest.cpp \
  source/model/BatchResultErrorEntry.cpp \
  source/model/CheckIfPhoneNumberIsOptedOutRequest.cpp \
  source/model/CheckIfPhoneNumberIsOptedOutResult.cpp \
  source/model/ConfirmSubscriptionRequest.cpp \
  source/model/ConfirmSubscriptionResult.cpp \
  source/model/CreatePlatformApplicationRequest.cpp \
  source/model/CreatePlatformApplicationResult.cpp \
  source/model/CreatePlatformEndpointRequest.cpp \
  source/model/CreatePlatformEndpointResult.cpp \
  source/model/CreateSMSSandboxPhoneNumberRequest.cpp \
  source/model/CreateSMSSandboxPhoneNumberResult.cpp \
  source/model/CreateTopicRequest.cpp \
  source/model/CreateTopicResult.cpp \
  source/model/DeleteEndpointRequest.cpp \
  source/model/DeletePlatformApplicationRequest.cpp \
  source/model/DeleteSMSSandboxPhoneNumberRequest.cpp \
  source/model/DeleteSMSSandboxPhoneNumberResult.cpp \
  source/model/DeleteTopicRequest.cpp \
  source/model/GetDataProtectionPolicyRequest.cpp \
  source/model/GetDataProtectionPolicyResult.cpp \
  source/model/GetEndpointAttributesRequest.cpp \
  source/model/GetEndpointAttributesResult.cpp \
  source/model/GetPlatformApplicationAttributesRequest.cpp \
  source/model/GetPlatformApplicationAttributesResult.cpp \
  source/model/GetSMSAttributesRequest.cpp \
  source/model/GetSMSAttributesResult.cpp \
  source/model/GetSMSSandboxAccountStatusRequest.cpp \
  source/model/GetSMSSandboxAccountStatusResult.cpp \
  source/model/GetSubscriptionAttributesRequest.cpp \
  source/model/GetSubscriptionAttributesResult.cpp \
  source/model/GetTopicAttributesRequest.cpp \
  source/model/GetTopicAttributesResult.cpp \
  source/model/LanguageCodeString.cpp \
  source/model/ListEndpointsByPlatformApplicationRequest.cpp \
  source/model/ListEndpointsByPlatformApplicationResult.cpp \
  source/model/ListOriginationNumbersRequest.cpp \
  source/model/ListOriginationNumbersResult.cpp \
  source/model/ListPhoneNumbersOptedOutRequest.cpp \
  source/model/ListPhoneNumbersOptedOutResult.cpp \
  source/model/ListPlatformApplicationsRequest.cpp \
  source/model/ListPlatformApplicationsResult.cpp \
  source/model/ListSMSSandboxPhoneNumbersRequest.cpp \
  source/model/ListSMSSandboxPhoneNumbersResult.cpp \
  source/model/ListSubscriptionsByTopicRequest.cpp \
  source/model/ListSubscriptionsByTopicResult.cpp \
  source/model/ListSubscriptionsRequest.cpp \
  source/model/ListSubscriptionsResult.cpp \
  source/model/ListTagsForResourceRequest.cpp \
  source/model/ListTagsForResourceResult.cpp \
  source/model/ListTopicsRequest.cpp \
  source/model/ListTopicsResult.cpp \
  source/model/MessageAttributeValue.cpp \
  source/model/NumberCapability.cpp \
  source/model/OptInPhoneNumberRequest.cpp \
  source/model/OptInPhoneNumberResult.cpp \
  source/model/PhoneNumberInformation.cpp \
  source/model/PlatformApplication.cpp \
  source/model/PublishBatchRequest.cpp \
  source/model/PublishBatchRequestEntry.cpp \
  source/model/PublishBatchResult.cpp \
  source/model/PublishBatchResultEntry.cpp \
  source/model/PublishRequest.cpp \
  source/model/PublishResult.cpp \
  source/model/PutDataProtectionPolicyRequest.cpp \
  source/model/RemovePermissionRequest.cpp \
  source/model/ResponseMetadata.cpp \
  source/model/RouteType.cpp \
  source/model/SMSSandboxPhoneNumber.cpp \
  source/model/SMSSandboxPhoneNumberVerificationStatus.cpp \
  source/model/SetEndpointAttributesRequest.cpp \
  source/model/SetPlatformApplicationAttributesRequest.cpp \
  source/model/SetSMSAttributesRequest.cpp \
  source/model/SetSMSAttributesResult.cpp \
  source/model/SetSubscriptionAttributesRequest.cpp \
  source/model/SetTopicAttributesRequest.cpp \
  source/model/SubscribeRequest.cpp \
  source/model/SubscribeResult.cpp \
  source/model/Subscription.cpp \
  source/model/Tag.cpp \
  source/model/TagResourceRequest.cpp \
  source/model/TagResourceResult.cpp \
  source/model/Topic.cpp \
  source/model/UnsubscribeRequest.cpp \
  source/model/UntagResourceRequest.cpp \
  source/model/UntagResourceResult.cpp \
  source/model/VerificationException.cpp \
  source/model/VerifySMSSandboxPhoneNumberRequest.cpp \
  source/model/VerifySMSSandboxPhoneNumberResult.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include/aws/sns \
  $(MY_MODULE_PATH)/include/aws/sns/model \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/bearer-token-provider \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/signer \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/auth/signer-provider \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/client \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/config \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/config/defaults \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/endpoint \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/endpoint/internal \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external/cjson \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/external/tinyxml2 \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http/curl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/http/standard \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/internal \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/monitoring \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/net \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/platform \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/platform/refs \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/base64 \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/bcrypt \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/commoncrypto \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/crypto/openssl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/event \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/json \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/logging \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/logging/android \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/memory \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/memory/stl \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/ratelimiter \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/stream \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/threading \
  $(MY_MODULE_PATH)/../aws-cpp-sdk-core/include/aws/core/utils/xml \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-auth/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-cal/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-common/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-compression/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-event-stream/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-http/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-io/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-io/source \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-mqtt/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-s3/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-c-sdkutils/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/crt/aws-checksums/include \
  $(MY_MODULE_PATH)/../aws-crt-cpp/include \
  $(MY_MODULE_PATH)/../curl/include \
  $(MY_MODULE_PATH)/../curl/include/curl \
  $(MY_MODULE_PATH)/../curl/lib \
  $(MY_MODULE_PATH)/../curl/lib/vauth \
  $(MY_MODULE_PATH)/../curl/lib/vquic \
  $(MY_MODULE_PATH)/../curl/lib/vssh \
  $(MY_MODULE_PATH)/../curl/lib/vtls \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/include/aws

LOCAL_CFLAGS := -DAWS_SNS_EXPORTS -DUSE_IMPORT_EXPORT=1


LOCAL_SHARED_LIBRARIES := \
  aws-cpp-sdk-core

include $(BUILD_SHARED_LIBRARY)

