--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefLOADER


project( "gucefLOADER" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT" } )


configuration( {} )
defines( { "GUCEF_CORE_EMBED_CODE", "GUCEF_LOADER_BUILD_MODULE", "GUCEF_MT_EMBED_CODE", "GUCEF_NO_LOGGING", "MODULE_CONSENSUS_NAME=gucefLOADER", "MODULE_NAME=gucefLOADER", "MODULE_SEMVER=0_1_0_0" } )
  links( { "dl", "log" } )
  links( { "dl", "log" } )
  links( { "dl", "rt" } )
  links( { "dl", "rt" } )
  links( { "PowrProf.lib", "Ws2_32.lib", "winmm.lib" } )
  links( { "PowrProf.lib", "Ws2_32.lib", "winmm.lib" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "../gucefCORE/include/CDynamicBuffer.h",
  "../gucefCORE/include/CDynamicBufferAccess.h",
  "../gucefCORE/include/CException.h",
  "../gucefCORE/include/CFileAccess.h",
  "../gucefCORE/include/CICloneable.h",
  "../gucefCORE/include/CIOAccess.h",
  "../gucefCORE/include/CMsgException.h",
  "../gucefCORE/include/DVCPPOSWRAP.h",
  "../gucefCORE/include/DVOSWRAP.h",
  "../gucefCORE/include/MFILE.h",
  "../gucefCORE/include/PAFILE.h",
  "../gucefCORE/include/dvcppfileutils.h",
  "../gucefCORE/include/dvcppstringutils.h",
  "../gucefCORE/include/dvfileutils.h",
  "../gucefCORE/include/dvmd5utils.h",
  "../gucefCORE/include/dvstrutils.h",
  "../gucefCORE/include/gucefCORE_CAsciiString.h",
  "../gucefCORE/include/gucefCORE_CDate.h",
  "../gucefCORE/include/gucefCORE_CDateTime.h",
  "../gucefCORE/include/gucefCORE_CIDate.h",
  "../gucefCORE/include/gucefCORE_CITime.h",
  "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
  "../gucefCORE/include/gucefCORE_CString.h",
  "../gucefCORE/include/gucefCORE_CTime.h",
  "../gucefCORE/include/gucefCORE_CUtf8String.h",
  "../gucefCORE/include/gucefCORE_CVariant.h",
  "../gucefCORE/include/md5.h",
  "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
  "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
  "../gucefMT/include/gucefMT_CICloneable.h",
  "../gucefMT/include/gucefMT_CILockable.h",
  "../gucefMT/include/gucefMT_CMutex.h",
  "../gucefMT/include/gucefMT_CNoLock.h",
  "../gucefMT/include/gucefMT_CScopeMutex.h",
  "../gucefMT/include/gucefMT_LockStatus.h",
  "../gucefMT/include/gucefMT_ThreadStatus.h",
  "../gucefMT/include/gucefMT_dvmtoswrap.h",
  "../gucefMT/include/gucefMT_mutex.h",
  "include/gucefLOADER.h",
  "include/gucefLOADER_ETypes.h",
  "include/gucefLOADER_config.h",
  "include/gucefLOADER_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "../gucefCORE/src/CDynamicBuffer.cpp",
  "../gucefCORE/src/CDynamicBufferAccess.cpp",
  "../gucefCORE/src/CException.cpp",
  "../gucefCORE/src/CFileAccess.cpp",
  "../gucefCORE/src/CICloneable.cpp",
  "../gucefCORE/src/CIOAccess.cpp",
  "../gucefCORE/src/CMsgException.cpp",
  "../gucefCORE/src/DVCPPOSWRAP.cpp",
  "../gucefCORE/src/DVOSWRAP.cpp",
  "../gucefCORE/src/IOACCESS.c",
  "../gucefCORE/src/MFILE.c",
  "../gucefCORE/src/PAFILE.c",
  "../gucefCORE/src/dvcppfileutils.cpp",
  "../gucefCORE/src/dvcppstringutils.cpp",
  "../gucefCORE/src/dvfileutils.cpp",
  "../gucefCORE/src/dvmd5utils.c",
  "../gucefCORE/src/dvstrutils.cpp",
  "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
  "../gucefCORE/src/gucefCORE_CDate.cpp",
  "../gucefCORE/src/gucefCORE_CDateTime.cpp",
  "../gucefCORE/src/gucefCORE_CIDate.cpp",
  "../gucefCORE/src/gucefCORE_CITime.cpp",
  "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
  "../gucefCORE/src/gucefCORE_CTime.cpp",
  "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
  "../gucefCORE/src/gucefCORE_CVariant.cpp",
  "../gucefCORE/src/md5.c",
  "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
  "../gucefMT/src/gucefMT_CICloneable.cpp",
  "../gucefMT/src/gucefMT_CILockable.cpp",
  "../gucefMT/src/gucefMT_CMutex.cpp",
  "../gucefMT/src/gucefMT_CNoLock.cpp",
  "../gucefMT/src/gucefMT_CScopeMutex.cpp",
  "../gucefMT/src/gucefMT_LockStatus.cpp",
  "../gucefMT/src/gucefMT_ThreadStatus.cpp",
  "../gucefMT/src/gucefMT_dvmtoswrap.c",
  "../gucefMT/src/gucefMT_mutex.c",
  "src/gucefLOADER.cpp"
 } )



configuration( { "ANDROID32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "ANDROID64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "ARDUINO" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "EMSCRIPTEN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "EMSCRIPTEN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "GLX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "GTK" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "IOS" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "LINUX32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "NACL" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "OSX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "POSIX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "SDL" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "SYMBIAN" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "UNIX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefCORE/include/mswin/gucefCORE_mswinutils.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h",
      "../gucefMT/include/mswin/gucefMT_mswinutils.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefCORE/src/mswin/gucefCORE_mswinutils.cpp",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c",
      "../gucefMT/src/mswin/gucefMT_mswinutils.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../gucefCORE/include/CDynamicBuffer.h",
      "../gucefCORE/include/CDynamicBufferAccess.h",
      "../gucefCORE/include/CException.h",
      "../gucefCORE/include/CFileAccess.h",
      "../gucefCORE/include/CICloneable.h",
      "../gucefCORE/include/CIOAccess.h",
      "../gucefCORE/include/CMsgException.h",
      "../gucefCORE/include/DVCPPOSWRAP.h",
      "../gucefCORE/include/DVOSWRAP.h",
      "../gucefCORE/include/MFILE.h",
      "../gucefCORE/include/PAFILE.h",
      "../gucefCORE/include/dvcppfileutils.h",
      "../gucefCORE/include/dvcppstringutils.h",
      "../gucefCORE/include/dvfileutils.h",
      "../gucefCORE/include/dvmd5utils.h",
      "../gucefCORE/include/dvstrutils.h",
      "../gucefCORE/include/gucefCORE_CAsciiString.h",
      "../gucefCORE/include/gucefCORE_CDate.h",
      "../gucefCORE/include/gucefCORE_CDateTime.h",
      "../gucefCORE/include/gucefCORE_CIDate.h",
      "../gucefCORE/include/gucefCORE_CITime.h",
      "../gucefCORE/include/gucefCORE_CResourceMetaData.h",
      "../gucefCORE/include/gucefCORE_CString.h",
      "../gucefCORE/include/gucefCORE_CTime.h",
      "../gucefCORE/include/gucefCORE_CUtf8String.h",
      "../gucefCORE/include/gucefCORE_CVariant.h",
      "../gucefCORE/include/md5.h",
      "../gucefCORE/include/c_api/gucefCORE_c_ioaccess.h",
      "../gucefCORE/include/c_api/gucefCORE_c_variantdata.h",
      "../gucefCORE/include/mswin/gucefCORE_mswinutils.h",
      "../gucefMT/include/gucefMT_CICloneable.h",
      "../gucefMT/include/gucefMT_CILockable.h",
      "../gucefMT/include/gucefMT_CMutex.h",
      "../gucefMT/include/gucefMT_CNoLock.h",
      "../gucefMT/include/gucefMT_CScopeMutex.h",
      "../gucefMT/include/gucefMT_LockStatus.h",
      "../gucefMT/include/gucefMT_ThreadStatus.h",
      "../gucefMT/include/gucefMT_dvmtoswrap.h",
      "../gucefMT/include/gucefMT_mutex.h",
      "../gucefMT/include/mswin/gucefMT_mswinutils.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../gucefCORE/src/CDynamicBuffer.cpp",
      "../gucefCORE/src/CDynamicBufferAccess.cpp",
      "../gucefCORE/src/CException.cpp",
      "../gucefCORE/src/CFileAccess.cpp",
      "../gucefCORE/src/CICloneable.cpp",
      "../gucefCORE/src/CIOAccess.cpp",
      "../gucefCORE/src/CMsgException.cpp",
      "../gucefCORE/src/DVCPPOSWRAP.cpp",
      "../gucefCORE/src/DVOSWRAP.cpp",
      "../gucefCORE/src/IOACCESS.c",
      "../gucefCORE/src/MFILE.c",
      "../gucefCORE/src/PAFILE.c",
      "../gucefCORE/src/dvcppfileutils.cpp",
      "../gucefCORE/src/dvcppstringutils.cpp",
      "../gucefCORE/src/dvfileutils.cpp",
      "../gucefCORE/src/dvmd5utils.c",
      "../gucefCORE/src/dvstrutils.cpp",
      "../gucefCORE/src/gucefCORE_CAsciiString.cpp",
      "../gucefCORE/src/gucefCORE_CDate.cpp",
      "../gucefCORE/src/gucefCORE_CDateTime.cpp",
      "../gucefCORE/src/gucefCORE_CIDate.cpp",
      "../gucefCORE/src/gucefCORE_CITime.cpp",
      "../gucefCORE/src/gucefCORE_CResourceMetaData.cpp",
      "../gucefCORE/src/gucefCORE_CTime.cpp",
      "../gucefCORE/src/gucefCORE_CUtf8String.cpp",
      "../gucefCORE/src/gucefCORE_CVariant.cpp",
      "../gucefCORE/src/md5.c",
      "../gucefCORE/src/c_api/gucefCORE_c_variantdata.c",
      "../gucefCORE/src/mswin/gucefCORE_mswinutils.cpp",
      "../gucefMT/src/gucefMT_CICloneable.cpp",
      "../gucefMT/src/gucefMT_CILockable.cpp",
      "../gucefMT/src/gucefMT_CMutex.cpp",
      "../gucefMT/src/gucefMT_CNoLock.cpp",
      "../gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../gucefMT/src/gucefMT_LockStatus.cpp",
      "../gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../gucefMT/src/gucefMT_dvmtoswrap.c",
      "../gucefMT/src/gucefMT_mutex.c",
      "../gucefMT/src/mswin/gucefMT_mswinutils.cpp"
    } )


configuration( {} )
includedirs( { "..", "../../common/include", "../gucefCORE", "../gucefCORE/include", "../gucefCORE/include/c_api", "../gucefMT", "../gucefMT/include", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../gucefCORE/include/android", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "ANDROID64" } )
includedirs( { "../gucefCORE/include/android", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "ARDUINO" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "GLX" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "GTK" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "IOS" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "LINUX32" } )
includedirs( { "../gucefCORE/include/linux", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "LINUX64" } )
includedirs( { "../gucefCORE/include/linux", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "NACL" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "OSX" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "POSIX" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "SDL" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "SYMBIAN" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "UNIX" } )
includedirs( { "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefMT/include/" } )

configuration( { "WIN32" } )
includedirs( { "../gucefCORE/include/mswin", "../gucefMT/include/mswin", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefCORE/include/mswin/", "../gucefMT/include/", "../gucefMT/include/mswin/" } )

configuration( { "WIN64" } )
includedirs( { "../gucefCORE/include/mswin", "../gucefMT/include/mswin", "../gucefCORE/include/", "../gucefCORE/include/c_api/", "../gucefCORE/include/mswin/", "../gucefMT/include/", "../gucefMT/include/mswin/" } )
