#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := gucefKAITAI
LOCAL_MODULE_FILENAME := libgucefKAITAI
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/gucefKAITAI_CGlobalKaitaiSchemaRegistry.cpp \
  src/gucefKAITAI_CKaitaiDStoreCodec.cpp \
  src/gucefKAITAI_CKaitaiDataDrivenDStoreCodec.cpp \
  src/gucefKAITAI_CKaitaiDataDrivenDStoreCodecFactory.cpp \
  src/gucefKAITAI_CKaitaiGlobal.cpp \
  src/gucefKAITAI_CKaitaiReader.cpp \
  src/gucefKAITAI_CKaitaiSchema.cpp \
  src/gucefKAITAI_CKaitaiSchemaBaseField.cpp \
  src/gucefKAITAI_CKaitaiSchemaBasicField.cpp \
  src/gucefKAITAI_CKaitaiSchemaDelimitedField.cpp \
  src/gucefKAITAI_CKaitaiSchemaEnumDefinition.cpp \
  src/gucefKAITAI_CKaitaiSchemaFieldDefinition.cpp \
  src/gucefKAITAI_CKaitaiSchemaInstanceField.cpp \
  src/gucefKAITAI_CKaitaiSchemaOpaqueField.cpp \
  src/gucefKAITAI_CKaitaiSchemaRegistry.cpp \
  src/gucefKAITAI_CKaitaiSchemaStructureField.cpp \
  src/gucefKAITAI_CKaitaiSchemaSubstreamField.cpp \
  src/gucefKAITAI_CKaitaiSchemaSwitchField.cpp \
  src/gucefKAITAI_CModule.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/includes \
  $(MY_MODULE_PATH)/../../common/include \
  $(MY_MODULE_PATH)/../gucefCORE/include \
  $(MY_MODULE_PATH)/../gucefCORE/include/android \
  $(MY_MODULE_PATH)/../gucefCORE/include/c_api \
  $(MY_MODULE_PATH)/../gucefMT/include \
  $(MY_MODULE_PATH)/../gucefVFS/include

LOCAL_CFLAGS := -DGUCEF_KAITAI_BUILD_MODULE


LOCAL_SHARED_LIBRARIES := \
  gucefCORE \
  gucefMT \
  gucefVFS

include $(BUILD_SHARED_LIBRARY)

