--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefKAITAI


project( "gucefKAITAI" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "gucefVFS" } )
links( { "gucefCORE", "gucefMT", "gucefVFS" } )


configuration( {} )
defines( { "GUCEF_KAITAI_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "includes/gucefKAITAI.h",
  "includes/gucefKAITAI_CGlobalKaitaiSchemaRegistry.h",
  "includes/gucefKAITAI_CKaitaiDStoreCodec.h",
  "includes/gucefKAITAI_CKaitaiDataDrivenDStoreCodec.h",
  "includes/gucefKAITAI_CKaitaiDataDrivenDStoreCodecFactory.h",
  "includes/gucefKAITAI_CKaitaiGlobal.h",
  "includes/gucefKAITAI_CKaitaiReader.h",
  "includes/gucefKAITAI_CKaitaiSchema.h",
  "includes/gucefKAITAI_CKaitaiSchemaBaseField.h",
  "includes/gucefKAITAI_CKaitaiSchemaBasicField.h",
  "includes/gucefKAITAI_CKaitaiSchemaDelimitedField.h",
  "includes/gucefKAITAI_CKaitaiSchemaEnumDefinition.h",
  "includes/gucefKAITAI_CKaitaiSchemaFieldDefinition.h",
  "includes/gucefKAITAI_CKaitaiSchemaInstanceField.h",
  "includes/gucefKAITAI_CKaitaiSchemaOpaqueField.h",
  "includes/gucefKAITAI_CKaitaiSchemaRegistry.h",
  "includes/gucefKAITAI_CKaitaiSchemaStructureField.h",
  "includes/gucefKAITAI_CKaitaiSchemaSubstreamField.h",
  "includes/gucefKAITAI_CKaitaiSchemaSwitchField.h",
  "includes/gucefKAITAI_CKaitaiSerializer.h",
  "includes/gucefKAITAI_CModule.h",
  "includes/gucefKAITAI_ETypes.h",
  "includes/gucefKAITAI_config.h",
  "includes/gucefKAITAI_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/gucefKAITAI_CGlobalKaitaiSchemaRegistry.cpp",
  "src/gucefKAITAI_CKaitaiDStoreCodec.cpp",
  "src/gucefKAITAI_CKaitaiDataDrivenDStoreCodec.cpp",
  "src/gucefKAITAI_CKaitaiDataDrivenDStoreCodecFactory.cpp",
  "src/gucefKAITAI_CKaitaiGlobal.cpp",
  "src/gucefKAITAI_CKaitaiReader.cpp",
  "src/gucefKAITAI_CKaitaiSchema.cpp",
  "src/gucefKAITAI_CKaitaiSchemaBaseField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaBasicField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaDelimitedField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaEnumDefinition.cpp",
  "src/gucefKAITAI_CKaitaiSchemaFieldDefinition.cpp",
  "src/gucefKAITAI_CKaitaiSchemaInstanceField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaOpaqueField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaRegistry.cpp",
  "src/gucefKAITAI_CKaitaiSchemaStructureField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaSubstreamField.cpp",
  "src/gucefKAITAI_CKaitaiSchemaSwitchField.cpp",
  "src/gucefKAITAI_CModule.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../gucefCORE/include", "../gucefCORE/include/c_api", "../gucefMT/include", "../gucefVFS/include", "includes" } )

configuration( { "ANDROID" } )
includedirs( { "../gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../gucefCORE/include/mswin", "../gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../gucefCORE/include/mswin", "../gucefMT/include/mswin" } )
