apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: LoadBalancer  # Use NodePort if you don't have a cloud provider that supports LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
