--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: guidriverRmlUIOpenGL


project( "guidriverRmlUIOpenGL" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "RmlUI_Core", "gucefCORE", "gucefGUI", "gucefINPUT", "gucefMT", "guidriverRmlUI" } )
links( { "RmlUI_Core", "gucefCORE", "gucefGUI", "gucefINPUT", "gucefMT", "guidriverRmlUI" } )


configuration( {} )
defines( { "GUIDRIVERRMLUIGL_BUILD_MODULE", "MODULE_CONSENSUS_NAME=guidriverRmlUIOpenGL", "MODULE_IS_PLUGIN=1", "MODULE_NAME=guidriverRmlUIOpenGL" } )
  links( { "EGL", "GLESv1_CM" } )
  links( { "EGL", "GLESv1_CM" } )
  links( { "GL" } )
  links( { "GL" } )
  links( { "OpenGL32.lib" } )
  links( { "OpenGL32.lib" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/guidriverRmlUIOpenGL.h",
  "include/guidriverRmlUIOpenGL_CRocketGuiDriver.h",
  "include/guidriverRmlUIOpenGL_CRocketRenderInterfaceOpenGL.h",
  "include/guidriverRmlUIOpenGL_config.h",
  "include/guidriverRmlUIOpenGL_macros.h",
  "include/guidriverRmlUIOpenGL_pluginAPI.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/guidriverRmlUIOpenGL_CRocketGuiDriver.cpp",
  "src/guidriverRmlUIOpenGL_CRocketRenderInterfaceOpenGL.cpp",
  "src/guidriverRmlUIOpenGL_pluginAPI.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/RmlUi/Include", "../../../dependencies/RmlUi/Include/RmlUi", "../../../dependencies/RmlUi/Include/RmlUi/Config", "../../../dependencies/RmlUi/Include/RmlUi/Core", "../../../dependencies/RmlUi/Include/RmlUi/Core/Containers", "../../../dependencies/RmlUi/Include/RmlUi/Core/Containers/itlib", "../../../dependencies/RmlUi/Include/RmlUi/Core/Elements", "../../../dependencies/RmlUi/Include/RmlUi/Debugger", "../../../dependencies/RmlUi/Include/RmlUi/Lottie", "../../../dependencies/RmlUi/Include/RmlUi/Lua", "../../../dependencies/RmlUi/Include/RmlUi/SVG", "../../../dependencies/RmlUi/Source/Core", "../../../dependencies/RmlUi/Source/Core/Elements", "../../../dependencies/RmlUi/Source/Core/FontEngineDefault", "../../../dependencies/RmlUi/Source/Core/Layout", "../../../dependencies/freetype/include", "../../../dependencies/freetype/include/freetype", "../../../dependencies/freetype/include/freetype/config", "../../../dependencies/freetype/include/freetype/internal", "../../../dependencies/freetype/include/freetype/internal/services", "../../../dependencies/freetype/src", "../../../dependencies/freetype/src/winfonts", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefGUI/include", "../../../platform/gucefIMAGE/include", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include", "../../../platform/gucefVFS/include", "../guidriverRmlUI/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
