#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := libprotobuf
LOCAL_MODULE_FILENAME := liblibprotobuf
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  google/protobuf/any.cc \
  google/protobuf/any.pb.cc \
  google/protobuf/any_lite.cc \
  google/protobuf/api.pb.cc \
  google/protobuf/arena.cc \
  google/protobuf/arenastring.cc \
  google/protobuf/descriptor.cc \
  google/protobuf/descriptor.pb.cc \
  google/protobuf/descriptor_database.cc \
  google/protobuf/duration.pb.cc \
  google/protobuf/dynamic_message.cc \
  google/protobuf/empty.pb.cc \
  google/protobuf/extension_set.cc \
  google/protobuf/extension_set_heavy.cc \
  google/protobuf/field_mask.pb.cc \
  google/protobuf/generated_enum_util.cc \
  google/protobuf/generated_message_bases.cc \
  google/protobuf/generated_message_reflection.cc \
  google/protobuf/generated_message_tctable_full.cc \
  google/protobuf/generated_message_tctable_lite.cc \
  google/protobuf/generated_message_util.cc \
  google/protobuf/implicit_weak_message.cc \
  google/protobuf/inlined_string_field.cc \
  google/protobuf/map.cc \
  google/protobuf/map_field.cc \
  google/protobuf/message.cc \
  google/protobuf/message_lite.cc \
  google/protobuf/parse_context.cc \
  google/protobuf/reflection_ops.cc \
  google/protobuf/repeated_field.cc \
  google/protobuf/repeated_ptr_field.cc \
  google/protobuf/service.cc \
  google/protobuf/source_context.pb.cc \
  google/protobuf/struct.pb.cc \
  google/protobuf/text_format.cc \
  google/protobuf/timestamp.pb.cc \
  google/protobuf/type.pb.cc \
  google/protobuf/unknown_field_set.cc \
  google/protobuf/wire_format.cc \
  google/protobuf/wire_format_lite.cc \
  google/protobuf/wrappers.pb.cc \
  google/protobuf/compiler/code_generator.cc \
  google/protobuf/compiler/importer.cc \
  google/protobuf/compiler/parser.cc \
  google/protobuf/compiler/plugin.cc \
  google/protobuf/compiler/plugin.pb.cc \
  google/protobuf/io/coded_stream.cc \
  google/protobuf/io/gzip_stream.cc \
  google/protobuf/io/printer.cc \
  google/protobuf/io/strtod.cc \
  google/protobuf/io/tokenizer.cc \
  google/protobuf/io/zero_copy_stream.cc \
  google/protobuf/io/zero_copy_stream_impl.cc \
  google/protobuf/io/zero_copy_stream_impl_lite.cc \
  google/protobuf/stubs/bytestream.cc \
  google/protobuf/stubs/common.cc \
  google/protobuf/stubs/int128.cc \
  google/protobuf/stubs/status.cc \
  google/protobuf/stubs/statusor.cc \
  google/protobuf/stubs/stringpiece.cc \
  google/protobuf/stubs/stringprintf.cc \
  google/protobuf/stubs/structurally_valid.cc \
  google/protobuf/stubs/strutil.cc \
  google/protobuf/stubs/substitute.cc \
  google/protobuf/stubs/time.cc \
  google/protobuf/util/delimited_message_util.cc \
  google/protobuf/util/field_comparator.cc \
  google/protobuf/util/field_mask_util.cc \
  google/protobuf/util/json_util.cc \
  google/protobuf/util/message_differencer.cc \
  google/protobuf/util/time_util.cc \
  google/protobuf/util/type_resolver_util.cc \
  google/protobuf/util/internal/datapiece.cc \
  google/protobuf/util/internal/default_value_objectwriter.cc \
  google/protobuf/util/internal/error_listener.cc \
  google/protobuf/util/internal/field_mask_utility.cc \
  google/protobuf/util/internal/json_escaping.cc \
  google/protobuf/util/internal/json_objectwriter.cc \
  google/protobuf/util/internal/json_stream_parser.cc \
  google/protobuf/util/internal/object_writer.cc \
  google/protobuf/util/internal/proto_writer.cc \
  google/protobuf/util/internal/protostream_objectsource.cc \
  google/protobuf/util/internal/protostream_objectwriter.cc \
  google/protobuf/util/internal/type_info.cc \
  google/protobuf/util/internal/utility.cc

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/google/protobuf \
  $(MY_MODULE_PATH)/google/protobuf/compiler \
  $(MY_MODULE_PATH)/google/protobuf/io \
  $(MY_MODULE_PATH)/google/protobuf/stubs \
  $(MY_MODULE_PATH)/google/protobuf/util \
  $(MY_MODULE_PATH)/google/protobuf/util/internal \
  $(MY_MODULE_PATH)/ \
  $(MY_MODULE_PATH)/google

LOCAL_CFLAGS := -DLIBPROTOBUF_EXPORTS -DLIBPROTOC_EXPORTS -DPROTOBUF_USE_DLLS


LOCAL_LDLIBS := \
  -llog \
  -lz

include $(BUILD_SHARED_LIBRARY)

