--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: redis-plus-plus


project( "redis-plus-plus" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "StaticLib" )

configuration( {} )
links( { "hiredis" } )
links( { "hiredis" } )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=redis_plus_plus", "MODULE_NAME=redis_plus_plus", "REDIS_PLUS_PLUS_BUILD_TEST=OFF", "REDIS_PLUS_PLUS_CXX_STANDARD=11" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "cmd_formatter.h",
  "command.h",
  "command_args.h",
  "command_options.h",
  "connection.h",
  "connection_pool.h",
  "errors.h",
  "hiredis_features.h",
  "pipeline.h",
  "queued_redis.h",
  "queued_redis.hpp",
  "redis++.h",
  "redis.h",
  "redis.hpp",
  "redis_cluster.h",
  "redis_cluster.hpp",
  "redis_uri.h",
  "reply.h",
  "sentinel.h",
  "shards.h",
  "shards_pool.h",
  "subscriber.h",
  "transaction.h",
  "utils.h",
  "cxx11/sw/redis++/cxx_utils.h",
  "no_tls/sw/redis++/tls.h",
  "patterns/redlock.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "command.cpp",
  "command_options.cpp",
  "connection.cpp",
  "connection_pool.cpp",
  "crc16.cpp",
  "errors.cpp",
  "pipeline.cpp",
  "redis.cpp",
  "redis_cluster.cpp",
  "redis_uri.cpp",
  "reply.cpp",
  "sentinel.cpp",
  "shards.cpp",
  "shards_pool.cpp",
  "subscriber.cpp",
  "transaction.cpp",
  "patterns/redlock.cpp"
 } )


configuration( {} )
includedirs( { "../../", "../../../../", "../../../../hiredis", "cxx11", "cxx11/sw", "no_tls", "no_tls/sw", "../redis++", "cxx11/sw/redis++", "no_tls/sw/redis++", "patterns" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../../hiredis" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../../hiredis" } )

configuration( { "ARDUINO" } )
includedirs( { "../../../../hiredis" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../../../hiredis" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../../../hiredis" } )

configuration( { "IOS" } )
includedirs( { "../../../../hiredis" } )

configuration( { "LINUX32" } )
includedirs( { "../../../../hiredis" } )

configuration( { "LINUX64" } )
includedirs( { "../../../../hiredis" } )

configuration( { "OSX" } )
includedirs( { "../../../../hiredis" } )

configuration( { "WIN32" } )
includedirs( { "../../../../hiredis" } )

configuration( { "WIN64" } )
includedirs( { "../../../../hiredis" } )
