--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: dstorepluginJSONPARSER


project( "dstorepluginJSONPARSER" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "jsonbuilder", "jsonparser" } )
links( { "jsonbuilder", "jsonparser" } )


configuration( {} )
defines( { "DSTOREPLUGINJSONPARSER_BUILD_MODULE", "MODULE_CONSENSUS_NAME=dstorepluginJSONPARSER", "MODULE_IS_PLUGIN=1", "MODULE_NAME=dstorepluginJSONPARSER" } )
  

configuration( { EMSCRIPTEN32 } )
defines( { "MODULE_API_PREFIX=dstorepluginJSONPARSER" } )
  

configuration( { EMSCRIPTEN64 } )
defines( { "MODULE_API_PREFIX=dstorepluginJSONPARSER" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainDSTOREpluginJSONPARSER.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainDSTOREpluginJSONPARSER.c"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/android" } )

configuration( { "ARDUINO" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "IOS" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/linux" } )

configuration( { "OSX" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/json-builder", "../../../dependencies/json-parser", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
