--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: dstorepluginPARSIFALXML


project( "dstorepluginPARSIFALXML" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "libparsifal" } )
links( { "libparsifal" } )


configuration( {} )
defines( { "DSTOREPLUGINPARSIFALXML_BUILD_MODULE", "MODULE_CONSENSUS_NAME=dstorepluginPARSIFALXML", "MODULE_IS_PLUGIN=1", "MODULE_NAME=dstorepluginPARSIFALXML" } )
  

configuration( { EMSCRIPTEN32 } )
defines( { "MODULE_API_PREFIX=dstorepluginPARSIFALXML" } )
  

configuration( { EMSCRIPTEN64 } )
defines( { "MODULE_API_PREFIX=dstorepluginPARSIFALXML" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainDSTOREpluginPARSIFALXML.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainDSTOREpluginPARSIFALXML.c"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/libparsifal/include", "../../../dependencies/libparsifal/include/libparsifal", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
