apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-raid
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  diskSelector: "raid"
