--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: yaml


project( "yaml" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )


configuration( {} )
defines( { "HAVE_CONFIG_H", "MODULE_CONSENSUS_NAME=yaml", "MODULE_NAME=yaml", "YAML_DECLARE_EXPORT" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/yaml.h",
  "src/config.h",
  "src/yaml_private.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/api.c",
  "src/dumper.c",
  "src/emitter.c",
  "src/loader.c",
  "src/parser.c",
  "src/reader.c",
  "src/scanner.c",
  "src/writer.c"
 } )


configuration( {} )
includedirs( { "include", "src" } )
