--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--


workspace( "GUCEF_tag_obsolete" )

  platforms( { "ALL", "ANDROID32", "ANDROID64", "ARDUINO", "EMSCRIPTEN32", "EMSCRIPTEN64", "IOS", "LINUX32", "LINUX64", "OSX", "WIN32", "WIN64" } )

  location( "projects\premake5\targets" )

  --
  -- Includes for all modules in the solution:
  --

filter "ALL"

filter "ANDROID32"

filter "ANDROID64"

filter "ARDUINO"

filter "EMSCRIPTEN32"

filter "EMSCRIPTEN64"

filter "IOS"

filter "LINUX32"
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "tools/CMakeListGenerator" )

filter "LINUX64"
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "tools/CMakeListGenerator" )

filter "OSX"

filter "WIN32"
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "tools/CMakeListGenerator" )

filter "WIN64"
  include( "platform/gucefCORE" )
  include( "platform/gucefMT" )
  include( "tools/CMakeListGenerator" )
