apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid
provisioner: kubernetes.io/no-provisioner  # No dynamic provisioning
reclaimPolicy: Retain  # Retain the volume after PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Wait until a pod uses the PVC
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jbod
provisioner: kubernetes.io/no-provisioner  # No dynamic provisioning
reclaimPolicy: Retain  # Retain the volume after PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Wait until a pod uses the PVC

