apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid
provisioner: rancher.io/local-path  # k3s dynamic provisioning via local-path-provisioner
reclaimPolicy: Retain  # Retain the volume after PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Wait until a pod uses the PVC
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jbod
provisioner: rancher.io/local-path  # k3s dynamic provisioning via local-path-provisioner
reclaimPolicy: Retain  # Retain the volume after PVC is deleted
volumeBindingMode: WaitForFirstConsumer  # Wait until a pod uses the PVC

