--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: MemoryLeakFinder


configuration( { "WIN32" } )
  project( "MemoryLeakFinder" )

configuration( { "WIN64" } )
  project( "MemoryLeakFinder" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "ANDROID32" } )
language( "C++" )

configuration( { "ANDROID64" } )
language( "C++" )

configuration( { "ARDUINO" } )
language( "C++" )

configuration( { "EMSCRIPTEN32" } )
language( "C++" )

configuration( { "EMSCRIPTEN64" } )
language( "C++" )

configuration( { "GLX" } )
language( "C++" )

configuration( { "GTK" } )
language( "C++" )

configuration( { "IOS" } )
language( "C++" )

configuration( { "LINUX32" } )
language( "C++" )

configuration( { "LINUX64" } )
language( "C++" )

configuration( { "NACL" } )
language( "C++" )

configuration( { "OSX" } )
language( "C++" )

configuration( { "POSIX" } )
language( "C++" )

configuration( { "SDL" } )
language( "C++" )

configuration( { "SYMBIAN" } )
language( "C++" )

configuration( { "UNIX" } )
language( "C++" )

configuration( { "WIN32" } )
language( "C++" )

configuration( { "WIN64" } )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "SharedLib" )
configuration( { "WIN64" } )


configuration( { WIN64 } )
kind( "SharedLib" )
  links( { "Winmm" } )
  

configuration( { WIN32 } )
defines( { "GUCEF_CALLSTACK_TRACING_DISABLED", "GUCEF_CORE_EMBED_CODE", "GUCEF_DYNNEWON_DISABLED", "GUCEF_DRGUP_BUILD_MODULE", "GUCEF_MT_EMBED_CODE", "GUCEF_PLATFORM_LOCK_TRACER_DISABLED", "GUCEF_PLATFORM_MEMORY_LEAK_CHECKER_INCLUDES_OLEAPI", "MODULE_NAME=MemoryLeakFinder" } )
  links( { "Winmm" } )
  

configuration( { WIN64 } )
defines( { "GUCEF_CALLSTACK_TRACING_DISABLED", "GUCEF_CORE_EMBED_CODE", "GUCEF_DYNNEWON_DISABLED", "GUCEF_DRGUP_BUILD_MODULE", "GUCEF_MT_EMBED_CODE", "GUCEF_PLATFORM_LOCK_TRACER_DISABLED", "GUCEF_PLATFORM_MEMORY_LEAK_CHECKER_INCLUDES_OLEAPI", "MODULE_NAME=MemoryLeakFinder" } )


configuration( { "ANDROID32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "ANDROID64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "ARDUINO" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "EMSCRIPTEN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "EMSCRIPTEN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "GLX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "GTK" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "IOS" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "LINUX32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "LINUX64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "NACL" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "OSX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "POSIX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "SDL" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "SYMBIAN" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "UNIX" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "WIN32" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h",
      "../../platform/gucefMT/include/mswin/gucefMT_mswinutils.h",
      "include/gucefDRGUP_ETypes.h",
      "include/gucefDRGUP_MemoryManager.h",
      "include/gucefDRGUP_callstack.h",
      "include/gucefDRGUP_config.h",
      "include/gucefDRGUP_locktrace.h",
      "include/gucefDRGUP_macros.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "../../platform/gucefMT/src/mswin/gucefMT_mswinutils.cpp",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )



configuration( { "WIN64" } )
    vpaths { ["Platform Headers"] = { "**.h", "**.hpp", "**.hxx" } }
    files( {
      "../../platform/gucefMT/include/gucefMT_CILockable.h",
      "../../platform/gucefMT/include/gucefMT_CMutex.h",
      "../../platform/gucefMT/include/gucefMT_CReadWriteLock.h",
      "../../platform/gucefMT/include/gucefMT_CScopeMutex.h",
      "../../platform/gucefMT/include/gucefMT_CScopeRwLock.h",
      "../../platform/gucefMT/include/gucefMT_DVRWLOCK.h",
      "../../platform/gucefMT/include/gucefMT_LockStatus.h",
      "../../platform/gucefMT/include/gucefMT_ThreadStatus.h",
      "../../platform/gucefMT/include/gucefMT_dvmtoswrap.h",
      "../../platform/gucefMT/include/gucefMT_mutex.h",
      "../../platform/gucefMT/include/mswin/gucefMT_mswinutils.h",
      "include/gucefDRGUP_ETypes.h",
      "include/gucefDRGUP_MemoryManager.h",
      "include/gucefDRGUP_callstack.h",
      "include/gucefDRGUP_config.h",
      "include/gucefDRGUP_locktrace.h",
      "include/gucefDRGUP_macros.h"
    } )

    vpaths { ["Platform Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
    files( {
      "../../platform/gucefMT/src/gucefMT_CILockable.cpp",
      "../../platform/gucefMT/src/gucefMT_CMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CReadWriteLock.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeMutex.cpp",
      "../../platform/gucefMT/src/gucefMT_CScopeRwLock.cpp",
      "../../platform/gucefMT/src/gucefMT_DVRWLOCK.c",
      "../../platform/gucefMT/src/gucefMT_LockStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_MUTEX.c",
      "../../platform/gucefMT/src/gucefMT_ThreadStatus.cpp",
      "../../platform/gucefMT/src/gucefMT_dvmtoswrap.c",
      "../../platform/gucefMT/src/mswin/gucefMT_mswinutils.cpp",
      "src/gucefDRGUP_MemoryManager.cpp",
      "src/gucefDRGUP_callstack.cpp",
      "src/gucefDRGUP_locktrace.cpp"
    } )


configuration( {} )
includedirs( { "../../common/include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "ANDROID64" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "ARDUINO" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "GLX" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "GTK" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "IOS" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "LINUX32" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "LINUX64" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "NACL" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "OSX" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "POSIX" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "SDL" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "SYMBIAN" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "UNIX" } )
includedirs( { "../../platform/gucefMT/include/" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin/", "include" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefMT/include/", "../../platform/gucefMT/include/mswin/", "include" } )
