--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: pubsubpluginFIX


project( "pubsubpluginFIX" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB" } )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=pubsubpluginFIX", "MODULE_IS_PLUGIN=1", "MODULE_NAME=pubsubpluginFIX", "PUBSUBPLUGIN_FIX_BUILD_PLUGIN_DLL" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/pubsubpluginFIX.h",
  "include/pubsubpluginFIX_CFIXMessage.h",
  "include/pubsubpluginFIX_CFIXPubSubClient.h",
  "include/pubsubpluginFIX_CFIXPubSubClientConfig.h",
  "include/pubsubpluginFIX_CFIXPubSubClientTopic.h",
  "include/pubsubpluginFIX_CFIXPubSubClientTopicConfig.h",
  "include/pubsubpluginFIX_config.h",
  "include/pubsubpluginFIX_macros.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/pubsubpluginFIX.cpp",
  "src/pubsubpluginFIX_CFIXMessage.cpp",
  "src/pubsubpluginFIX_CFIXPubSubClient.cpp",
  "src/pubsubpluginFIX_CFIXPubSubClientConfig.cpp",
  "src/pubsubpluginFIX_CFIXPubSubClientTopic.cpp",
  "src/pubsubpluginFIX_CFIXPubSubClientTopicConfig.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCOM/include", "../../../platform/gucefCOMCORE/include", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "../../../platform/gucefPUBSUB/include", "../../../platform/gucefVFS/include", "../../../platform/gucefWEB/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../../platform/gucefCOMCORE/include/linux", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../platform/gucefCOMCORE/include/linux", "../../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../../platform/gucefCOMCORE/include/mswin", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../platform/gucefCOMCORE/include/mswin", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
