# jenkins.yaml
jenkins:
  securityRealm:
    local:
      allowsSignup: true
      users:
        - id: "admin"
          password: "admin_password"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
  systemMessage: "Welcome to Jenkins!"
