apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              echo "Before permissions fix: (jenkins_home)";
              ls -ld /var/jenkins_home;
              ls -l /var/jenkins_home;
              echo "Fixing permissions... (jenkins_home)";
              chown -R 1000:1000 /var/jenkins_home;
              echo "After permissions fix: (jenkins_home)";
              ls -ld /var/jenkins_home;
              ls -l /var/jenkins_home;
              echo "Before permissions fix: (jenkins_home/data)";
              ls -ld /var/jenkins_home/data;
              ls -l /var/jenkins_home/data;
              echo "Fixing permissions... (jenkins_home/data)";
              chown -R 1000:1000 /var/jenkins_home/data;
              echo "After permissions fix: (jenkins_home/data)";
              ls -ld /var/jenkins_home/data;
              ls -l /var/jenkins_home/data;
          securityContext:
            runAsUser: 0  # Ensure root privileges for the initContainer to run chown
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home/data
      containers:
        - name: jenkins
          # Reference our locally created image
          image: vanvelzen/jenkins-server-base:latest

          # if you created the image locally you can set the imagePullPolicy not to pull
          # this is one way of avoiding the 'ErrImagePull' problem since k3s wont check its registries for the image
          imagePullPolicy: Never

          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          env:
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/casc_configs/jenkins_config.yaml"
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home/data
            - name: jenkins-workspace
              mountPath: /var/jenkins_home/workspace
            - name: jenkins-casc-volume
              mountPath: /var/jenkins_home/casc_configs
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
        - name: jenkins-workspace
          persistentVolumeClaim:
              claimName: jenkins-pv-workspace-claim
        - name: jenkins-casc-volume
          configMap:
            name: jenkins-casc

