--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: gucefPUBSUB_TestApp


project( "gucefPUBSUB_TestApp" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "WIN32" } )


configuration( { WIN32 } )
kind( "WindowedApp" )
configuration( { "NOT WIN32" } )
  

configuration( {} )
kind( "ConsoleApp" )

configuration( {} )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB", "gucefVFS", "gucefWEB" } )
links( { "gucefCOMCORE", "gucefCORE", "gucefMT", "gucefPUBSUB", "gucefVFS", "gucefWEB" } )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=gucefPUBSUB_TestApp", "MODULE_NAME=gucefPUBSUB_TestApp" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/MockPubSubClient.h",
  "include/TestBasicPubSubMsg.h",
  "include/TestCode_PubSubMsgBinaryStorageTest.h",
  "include/TestPubSubBookmark.h",
  "include/TestPubSubClientConfig.h",
  "include/TestPubSubClientFeatures.h",
  "include/TestPubSubClientSide.h",
  "include/TestPubSubFlowRouter.h",
  "include/TestPubSubFlowRouterConfig.h",
  "include/TestPubSubMsgBinarySerializer.h",
  "include/TestPubSubMsgContainerBinarySerializer.h",
  "include/TestPubSubPlugin_AWSSNS.h",
  "include/TestPubSubPlugin_AWSSQS.h",
  "include/TestPubSubPlugin_FIX.h",
  "include/TestPubSubPlugin_KAFKA.h",
  "include/TestPubSubPlugin_MSMQ.h",
  "include/TestPubSubPlugin_REDISCLUSTER.h",
  "include/TestPubSubPlugin_STORAGE.h",
  "include/TestPubSubPlugin_TEST.h",
  "include/TestPubSubPlugin_UDP.h",
  "include/TestPubSubPlugin_WEB.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/MockPubSubClient.cpp",
  "src/TestBasicPubSubMsg.cpp",
  "src/TestCode_PubSubMsgBinaryStorageTest.cpp",
  "src/TestPubSubBookmark.cpp",
  "src/TestPubSubClientConfig.cpp",
  "src/TestPubSubClientFeatures.cpp",
  "src/TestPubSubClientSide.cpp",
  "src/TestPubSubFlowRouter.cpp",
  "src/TestPubSubFlowRouterConfig.cpp",
  "src/TestPubSubMsgBinarySerializer.cpp",
  "src/TestPubSubMsgContainerBinarySerializer.cpp",
  "src/TestPubSubPlugin_AWSSNS.cpp",
  "src/TestPubSubPlugin_AWSSQS.cpp",
  "src/TestPubSubPlugin_FIX.cpp",
  "src/TestPubSubPlugin_KAFKA.cpp",
  "src/TestPubSubPlugin_MSMQ.cpp",
  "src/TestPubSubPlugin_REDISCLUSTER.cpp",
  "src/TestPubSubPlugin_STORAGE.cpp",
  "src/TestPubSubPlugin_TEST.cpp",
  "src/TestPubSubPlugin_UDP.cpp",
  "src/TestPubSubPlugin_WEB.cpp",
  "src/gucefPUBSUB_TestApp.cpp",
  "src/gucefPUBSUB_TestApp_main.cpp"
 } )


configuration( {} )
includedirs( { "../../common/include", "../../platform/gucefCOM/include", "../../platform/gucefCOMCORE/include", "../../platform/gucefCORE/include", "../../platform/gucefCORE/include/c_api", "../../platform/gucefMT/include", "../../platform/gucefPUBSUB/include", "../../platform/gucefVFS/include", "../../platform/gucefWEB/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../platform/gucefCORE/include/android" } )

configuration( { "LINUX32" } )
includedirs( { "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../platform/gucefCOMCORE/include/linux", "../../platform/gucefCORE/include/linux" } )

configuration( { "WIN32" } )
includedirs( { "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../platform/gucefCOMCORE/include/mswin", "../../platform/gucefCORE/include/mswin", "../../platform/gucefMT/include/mswin" } )
