--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: inputdriverNANDROID


configuration( { "ANDROID32" } )
  project( "inputdriverNANDROID" )

configuration( { "ANDROID64" } )
  project( "inputdriverNANDROID" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C" )

configuration( { "ANDROID32" } )


configuration( { ANDROID32 } )
kind( "SharedLib" )
configuration( { "ANDROID64" } )


configuration( { ANDROID64 } )
kind( "SharedLib" )


configuration( {} )
defines( { "MODULE_CONSENSUS_NAME=inputdriverNANDROID" } )
  
configuration( { ANDROID32 } )
links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "android", "android_native_app_glue", "gucefCORE", "gucefINPUT", "gucefMT" } )
  

configuration( { ANDROID32 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVERANDROID_BUILD_MODULE", "MODULE_IS_PLUGIN=1", "MODULE_NAME=inputdriverNANDROID" } )
  
configuration( { ANDROID64 } )
links( { "gucefCORE", "gucefINPUT", "gucefMT" } )
  links( { "android", "android_native_app_glue", "gucefCORE", "gucefINPUT", "gucefMT" } )
  

configuration( { ANDROID64 } )
defines( { "BUILD_GUCEF_INPUT_PLUGIN_DLL", "INPUTDRIVERANDROID_BUILD_MODULE", "MODULE_IS_PLUGIN=1", "MODULE_NAME=inputdriverNANDROID" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/inputdriverNANDROID.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/inputdriverNANDROID.c"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefINPUT/include", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../platform/gucefCORE/include/android" } )
