#-------------------------------------------------------------------
# This file has been automatically generated by ProjectGenerator    
# which is part of a build system designed for GUCEF                
#     (Galaxy Unlimited Framework)                                  
# For the latest info, see http://www.VanvelzenSoftware.com/        
#                                                                   
# The contents of this file are placed in the public domain. Feel   
# free to make use of it in any way you like.                       
#-------------------------------------------------------------------


ifndef MY_MODULE_PATH
  MY_MODULE_PATH := $(call my-dir)
endif
LOCAL_PATH := $(MY_MODULE_PATH)

include $(CLEAR_VARS)

@echo Module path: $(MY_MODULE_PATH)
LOCAL_MODULE := dstorepluginPROTOBUF
LOCAL_MODULE_FILENAME := libdstorepluginPROTOBUF
@echo Module name: $(LOCAL_MODULE)

LOCAL_SRC_FILES := \
  src/DLLMainDSTOREpluginPROTOBUF.cpp

LOCAL_C_INCLUDES := \
  $(MY_MODULE_PATH)/include \
  $(MY_MODULE_PATH)/../../../common/include \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf/compiler \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf/io \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf/stubs \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf/util \
  $(MY_MODULE_PATH)/../../../dependencies/protobuf/src/google/protobuf/util/internal \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include/android \
  $(MY_MODULE_PATH)/../../../platform/gucefCORE/include/c_api \
  $(MY_MODULE_PATH)/../../../platform/gucefMT/include

LOCAL_CFLAGS := -DDSTOREPLUGINPROTOBUF_BUILD_MODULE -DPROTOBUF_USE_DLLS


LOCAL_SHARED_LIBRARIES := \
  libprotobuf

include $(BUILD_SHARED_LIBRARY)

