--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: dstorepluginPROTOBUF


project( "dstorepluginPROTOBUF" )

configuration( {} )
  location( os.getenv( "PM4OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM4TARGETDIR" ) )

configuration( {} )
language( "C++" )

configuration( { "EMSCRIPTEN32" } )


configuration( { EMSCRIPTEN32 } )
kind( "StaticLib" )
configuration( { "EMSCRIPTEN64" } )


configuration( { EMSCRIPTEN64 } )
kind( "StaticLib" )


configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "libprotobuf" } )
links( { "libprotobuf" } )


configuration( {} )
defines( { "DSTOREPLUGINPROTOBUF_BUILD_MODULE", "MODULE_CONSENSUS_NAME=dstorepluginPROTOBUF", "MODULE_IS_PLUGIN=1", "MODULE_NAME=dstorepluginPROTOBUF", "PROTOBUF_USE_DLLS" } )
  

configuration( { EMSCRIPTEN32 } )
defines( { "MODULE_API_PREFIX=dstorepluginPROTOBUF" } )
  

configuration( { EMSCRIPTEN64 } )
defines( { "MODULE_API_PREFIX=dstorepluginPROTOBUF" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainDSTOREpluginPROTOBUF.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainDSTOREpluginPROTOBUF.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/protobuf/src", "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID32" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../platform/gucefCORE/include/android" } )

configuration( { "ANDROID64" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../platform/gucefCORE/include/android" } )

configuration( { "ARDUINO" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "EMSCRIPTEN32" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "EMSCRIPTEN64" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "IOS" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "OSX" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
