--------------------------------------------------------------------
-- This file was automatically generated by ProjectGenerator
-- which is tooling part the build system designed for GUCEF
--     (Galaxy Unlimited Framework)
-- For the latest info, see http://www.VanvelzenSoftware.com/
--
-- The contents of this file are placed in the public domain. Feel
-- free to make use of it in any way you like.
--------------------------------------------------------------------
--

-- Configuration for module: dstorepluginPROTOBUF


project( "dstorepluginPROTOBUF" )

configuration( {} )
  location( os.getenv( "PM5OUTPUTDIR" ) )

configuration( {} )
  targetdir( os.getenv( "PM5TARGETDIR" ) )

configuration( {} )
language( "C++" )



configuration( {} )
kind( "SharedLib" )

configuration( {} )
links( { "gucefCORE", "gucefMT", "libprotobuf" } )
links( { "libprotobuf" } )


configuration( {} )
defines( { "DSTOREPLUGINPROTOBUF_BUILD_MODULE" } )


configuration( {} )
vpaths { ["Headers"] = { "**.h", "**.hpp", "**.hxx" } }
files( {
  "include/DLLMainDSTOREpluginPROTOBUF.h"
 } )



configuration( {} )
vpaths { ["Source"] = { "**.c", "**.cpp", "**.cs", "**.asm" } }
files( {
  "src/DLLMainDSTOREpluginPROTOBUF.cpp"
 } )


configuration( {} )
includedirs( { "../../../common/include", "../../../dependencies/protobuf/src", "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../platform/gucefCORE/include", "../../../platform/gucefCORE/include/c_api", "../../../platform/gucefMT/include", "include" } )

configuration( { "ANDROID" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../platform/gucefCORE/include/android" } )

configuration( { "ARDUINO" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "EMSCRIPTEN" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "GLX" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "GTK" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "IOS" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "LINUX32" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "LINUX64" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/linux" } )

configuration( { "NACL" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "OSX" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "POSIX" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "SDL" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "SYMBIAN" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "UNIX" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal" } )

configuration( { "WIN32" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )

configuration( { "WIN64" } )
includedirs( { "../../../dependencies/protobuf/src/google", "../../../dependencies/protobuf/src/google/protobuf", "../../../dependencies/protobuf/src/google/protobuf/compiler", "../../../dependencies/protobuf/src/google/protobuf/io", "../../../dependencies/protobuf/src/google/protobuf/stubs", "../../../dependencies/protobuf/src/google/protobuf/util", "../../../dependencies/protobuf/src/google/protobuf/util/internal", "../../../dependencies/zlib", "../../../platform/gucefCORE/include/mswin", "../../../platform/gucefMT/include/mswin" } )
