name: target_GUCEF_exe_MyGUI.SkinEditor

on:
  workflow_dispatch:
    inputs:
      archiveBuildArtifacts:
        description: 'Archive Build Artifacts?'
        required: false
        default: 'false'
      targetPlatform:
        description: 'Target platform to build?'
        required: false
        default: 'all'

jobs:

  GUCEF_exe_MyGUI_SkinEditor-all:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_MyGUI.SkinEditor
      TARGET_PLATFORM: all
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_MyGUI.SkinEditor
      PRODUCT_NAME: MyGUI.SkinEditor
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build MyGUI.SkinEditor for platform all
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-all/packages/*MyGUI.SkinEditor*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-all/packages/*MyGUI.SkinEditor*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-all/packages/*MyGUI.SkinEditor*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-all/packages/*MyGUI.SkinEditor*.tar.xz
  GUCEF_exe_MyGUI_SkinEditor-linux32:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_MyGUI.SkinEditor
      TARGET_PLATFORM: linux32
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_MyGUI.SkinEditor
      PRODUCT_NAME: MyGUI.SkinEditor
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build MyGUI.SkinEditor for platform linux32
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux32/packages/*MyGUI.SkinEditor*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux32/packages/*MyGUI.SkinEditor*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux32/packages/*MyGUI.SkinEditor*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux32/packages/*MyGUI.SkinEditor*.tar.xz
  GUCEF_exe_MyGUI_SkinEditor-linux64:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_MyGUI.SkinEditor
      TARGET_PLATFORM: linux64
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_MyGUI.SkinEditor
      PRODUCT_NAME: MyGUI.SkinEditor
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build MyGUI.SkinEditor for platform linux64
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux64/packages/*MyGUI.SkinEditor*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux64/packages/*MyGUI.SkinEditor*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux64/packages/*MyGUI.SkinEditor*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-linux64/packages/*MyGUI.SkinEditor*.tar.xz
  GUCEF_exe_MyGUI_SkinEditor-win32:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_MyGUI.SkinEditor
      TARGET_PLATFORM: win32
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_MyGUI.SkinEditor
      PRODUCT_NAME: MyGUI.SkinEditor
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build MyGUI.SkinEditor for platform win32
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-win32/packages/*MyGUI.SkinEditor*.zip
  GUCEF_exe_MyGUI_SkinEditor-win64:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_MyGUI.SkinEditor
      TARGET_PLATFORM: win64
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_MyGUI.SkinEditor
      PRODUCT_NAME: MyGUI.SkinEditor
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build MyGUI.SkinEditor for platform win64
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_MyGUI.SkinEditor-win64/packages/*MyGUI.SkinEditor*.zip
