name: target_GUCEF_exe_UdpTransformer

on:
  workflow_dispatch:
    inputs:
      archiveBuildArtifacts:
        description: 'Archive Build Artifacts?'
        required: false
        default: 'false'
      targetPlatform:
        description: 'Target platform to build?'
        required: false
        default: 'all'

jobs:

  GUCEF_exe_UdpTransformer-all:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_UdpTransformer
      TARGET_PLATFORM: all
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_UdpTransformer
      PRODUCT_NAME: UdpTransformer
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build UdpTransformer for platform all
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_UdpTransformer-all/packages/*UdpTransformer*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_UdpTransformer-all/packages/*UdpTransformer*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_UdpTransformer-all/packages/*UdpTransformer*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_UdpTransformer-all/packages/*UdpTransformer*.tar.xz
