name: target_GUCEF_exe_FileSorter

on:
  workflow_dispatch:
    inputs:
      archiveBuildArtifacts:
        description: 'Archive Build Artifacts?'
        required: false
        default: 'false'
      targetPlatform:
        description: 'Target platform to build?'
        required: false
        default: 'all'

jobs:

  GUCEF_exe_FileSorter-all:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_FileSorter
      TARGET_PLATFORM: all
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_FileSorter
      PRODUCT_NAME: FileSorter
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build FileSorter for platform all
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-all/packages/*FileSorter*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-all/packages/*FileSorter*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-all/packages/*FileSorter*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-all/packages/*FileSorter*.tar.xz
  GUCEF_exe_FileSorter-linux32:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_FileSorter
      TARGET_PLATFORM: linux32
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_FileSorter
      PRODUCT_NAME: FileSorter
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build FileSorter for platform linux32
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux32/packages/*FileSorter*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux32/packages/*FileSorter*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux32/packages/*FileSorter*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux32/packages/*FileSorter*.tar.xz
  GUCEF_exe_FileSorter-linux64:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_FileSorter
      TARGET_PLATFORM: linux64
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_FileSorter
      PRODUCT_NAME: FileSorter
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build FileSorter for platform linux64
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux64/packages/*FileSorter*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux64/packages/*FileSorter*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux64/packages/*FileSorter*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-linux64/packages/*FileSorter*.tar.xz
  GUCEF_exe_FileSorter-win32:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_FileSorter
      TARGET_PLATFORM: win32
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_FileSorter
      PRODUCT_NAME: FileSorter
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build FileSorter for platform win32
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-win32/packages/*FileSorter*.zip
  GUCEF_exe_FileSorter-win64:
    runs-on: self-hosted
    env:
      TARGET_NAME: GUCEF_exe_FileSorter
      TARGET_PLATFORM: win64
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_FileSorter
      PRODUCT_NAME: FileSorter
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build FileSorter for platform win64
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_FileSorter-win64/packages/*FileSorter*.zip
