name: target_GUCEF_exe_CMakeListGenerator

on: repository_dispatch

jobs:

  GUCEF_exe_CMakeListGenerator-all:
    if: github.event.client_payload.job == 'GUCEF_exe_CMakeListGenerator-all'
    runs-on: ubuntu-latest
    env:
      TARGET_NAME: GUCEF_exe_CMakeListGenerator
      TARGET_PLATFORM: all
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_CMakeListGenerator
      PRODUCT_NAME: CMakeListGenerator
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build CMakeListGenerator for platform all
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-all/packages/*CMakeListGenerator*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-all/packages/*CMakeListGenerator*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-all/packages/*CMakeListGenerator*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-all/packages/*CMakeListGenerator*.tar.xz
  GUCEF_exe_CMakeListGenerator-linux32:
    if: github.event.client_payload.job == 'GUCEF_exe_CMakeListGenerator-linux32'
    runs-on: ubuntu-latest
    env:
      TARGET_NAME: GUCEF_exe_CMakeListGenerator
      TARGET_PLATFORM: linux32
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_CMakeListGenerator
      PRODUCT_NAME: CMakeListGenerator
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build CMakeListGenerator for platform linux32
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux32/packages/*CMakeListGenerator*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux32/packages/*CMakeListGenerator*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux32/packages/*CMakeListGenerator*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux32/packages/*CMakeListGenerator*.tar.xz
  GUCEF_exe_CMakeListGenerator-linux64:
    if: github.event.client_payload.job == 'GUCEF_exe_CMakeListGenerator-linux64'
    runs-on: ubuntu-latest
    env:
      TARGET_NAME: GUCEF_exe_CMakeListGenerator
      TARGET_PLATFORM: linux64
      TARGET_PROJECT: projects/CMake/targets/GUCEF_exe_CMakeListGenerator
      PRODUCT_NAME: CMakeListGenerator
      CI_TOOL: GITHUB-ACTIONS
      BUILD_TOOL: CMAKE
    steps:
      - uses: actions/checkout@master
      - name: Build CMakeListGenerator for platform linux64
        run: ./projects/CI/targets/ci_build.sh
      - name: Archive Debian build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux64/packages/*CMakeListGenerator*.deb
      - name: Archive RPM build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RPM packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux64/packages/*CMakeListGenerator*.rpm
      - name: Archive Tarball - bz2 compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.bz2 packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux64/packages/*CMakeListGenerator*.tar.bz2
      - name: Archive Tarball - Xz compressed build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar.xz packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-linux64/packages/*CMakeListGenerator*.tar.xz
  GUCEF_exe_CMakeListGenerator-win32:
    if: github.event.client_payload.job == 'GUCEF_exe_CMakeListGenerator-win32'
    runs-on: windows-latest
    env:
      TARGET_NAME: GUCEF_exe_CMakeListGenerator
      TARGET_PLATFORM: win32
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_CMakeListGenerator
      PRODUCT_NAME: CMakeListGenerator
      CI_TOOL: GITHUB-ACTIONS
    steps:
      - uses: actions/checkout@master
      - name: Build CMakeListGenerator for platform win32
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-win32/packages/*CMakeListGenerator*.zip
  GUCEF_exe_CMakeListGenerator-win64:
    if: github.event.client_payload.job == 'GUCEF_exe_CMakeListGenerator-win64'
    runs-on: windows-latest
    env:
      TARGET_NAME: GUCEF_exe_CMakeListGenerator
      TARGET_PLATFORM: win64
      TARGET_PROJECT: projects\CMake\targets\GUCEF_exe_CMakeListGenerator
      PRODUCT_NAME: CMakeListGenerator
      CI_TOOL: GITHUB-ACTIONS
    steps:
      - uses: actions/checkout@master
      - name: Build CMakeListGenerator for platform win64
        run: .\projects\CI\targets\ci_build.ps1
      - name: Archive ZIP build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZIP packages
          path: |
            ./common/bin/GUCEF_exe_CMakeListGenerator-win64/packages/*CMakeListGenerator*.zip
